### ISSUE TITLE
Time in the future: Clock sync on host issue

### ISSUE THREAD

**Issue by geeohgeegeeoh** [RIPE-NCC/rpki-validator-3#102]
I just found my red-marked "MFT time in the future" was due to local clock sync: I was 1min out of alignment with my producer.

The *actual* time I remain red-marked is the resync interval, so as litte as 1min was causing more extended visible red-marked state.

1) could you add something like ```check your local clock: you may be running in the past```
2) could this be amber and not red?

**Comment by lolepezy** [comment]
Hi,

We've added the clock reminder. But are you sure you have seen a red-marked state? It is already amber, as it is a warning (like here, for example https://rpki-validator.ripe.net/trust-anchors/monitor/2).
