### ISSUE TITLE
Packaging refers to SNAPSHOT.jar when the jarfile has another name

### ISSUE THREAD

**Issue by geeohgeegeeoh** [RIPE-NCC/rpki-validator-3#106]
```
nong $ sudo cat nohup.out
Password:
[ warning ] Neither JAVA_CMD nor JAVA_HOME are set, will try to find java on path.
Error: Unable to access jarfile lib/rpki-validator-3.1-SNAPSHOT.jar
nong $
```

Fixed by linking lib/rpki-validator-3.jar to lib/rpki-validator-3.1-SNAPSHOT.jar

**Comment by lolepezy** [comment]
Hi,

How did you get the lib/rpki-validator-3.1-SNAPSHOT.jar? Neither RPM nor tar.gz refer to the snapshot. Did you build the validator yourself?

**Comment by geeohgeegeeoh** [comment]
Nope. This is the downloads you provide

G

**Comment by lolepezy** [comment]
Could you please more specific? We provide RPM package and a tarball, and neither of them, as I said, has rpki-validator-3.1-SNAPSHOT.jar in it. What did you download and where was the rpki-validator-3.1-SNAPSHOT.jar file? Could you send us the URL of the download?

**Comment by geeohgeegeeoh** [comment]
You misunderstood me. There IS NO FILE called snapshot, but there is an
embedded binary string referee to it, in the jar file you made.

The .sh invoked the jar you made. The jar looked for a snapshot named file,
failed to find it and the java process exited.

Try strings *.jar | grep -i snapshot

**Comment by lolepezy** [comment]
We believe it's been fixed by now, so closing the issue.
