### ISSUE TITLE
RTR-Server: Broken config in beta rpm

### ISSUE THREAD

**Issue by mroethke** [RIPE-NCC/rpki-validator-3#11]
In the rtr-server configuration file rpki.validator.validated.objects.uri property is not set. This causes the ROA fetch to fail. 
Since this is already fixed on master a simple rebuild of the rpm should suffice. Or at least this should be mentioned on the wiki page.

**Comment by timbru** [comment]
Hi,

There is an open pull request for this that is almost ready to be merged.

The current master fixes this by having a full duplicate .properties file for all properties used by the application - including things that shouldn't be touched. But the proper solution we're after is to have well defined defaults and a much smaller config file with the settings that can be overridden locally.

I will link the new RPMs when this is ready.

**Comment by timbru** [comment]
since it's taking a bit longer to get this merged, I have linked the wiki page to the latest master build for the moment.

**Comment by timbru** [comment]
This should be fixed with the latest master builds. We added a link to a repository for RPMs for master builds to the beta test wiki page.
