### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by dostalradim** [RIPE-NCC/rpki-validator-3#110]
Hi,

Server:
2x CPU, 5.6 GB RAM, Centos 7.7.1908, Java 1.8.0_222

And is running only rtr-server in 3.1-2019.10.18_12.15.36 application and rpki-validator in 3.1-2019.10.18_12.15.36 version. It is test environment and I have configured only one router for connecting to it.

And my CPU is still utilized to 100 % with java process of rpki-validator. I have almost default configuration except listening port and IP. No exception in logs with INFO severity configured. Is it  bug or it is typical behavior?

Thank you!

**Comment by lolepezy** [comment]
Hi,

Does it use 100% all the time? 

In principle, high CPU usage is fine in the beginning (first few minutes) but it shouldn't be the case after that, high CPU utilisation should happen in spikes after object updates.

Could you send us the content from these two end-points when you experience high CPU utilisation?
https://<validator>/api/healthcheck/backgrounds
https://<validator>/api/xodus/tx

**Comment by dostalradim** [comment]
Yes, it uses 100 % of CPU all the time. Look at this image with system load 5 min. averages.

![system_load](https://user-images.githubusercontent.com/9046924/67760338-7092d500-fa41-11e9-9198-5b84ddd62613.png)

This one looks interesting, can you recognize any problem?
![Snímek obrazovky 2019-10-29 v 11 46 45](https://user-images.githubusercontent.com/9046924/67760538-c9626d80-fa41-11e9-8b4c-c0cf56110aba.png)

/api/xodus/tx
![Snímek obrazovky 2019-10-29 v 11 48 18](https://user-images.githubusercontent.com/9046924/67760670-0169b080-fa42-11e9-8eaf-279ec3e54e67.png)
![Snímek obrazovky 2019-10-29 v 11 47 34](https://user-images.githubusercontent.com/9046924/67760607-e7c86900-fa41-11e9-8f04-aeaef996e5c3.png)

Thank you for very fast reply!

**Comment by lolepezy** [comment]
I was going to say that it should be much faster (because it take 30 seconds on average to revalidate the AfriNIC trust anchor, which is pretty small and 130 seconds for RIPE NCC's), but then looked at our 2 CPUs installation and it has also very high load average and similar execution times.

I can suggest you give it more CPU cores. We also have 4-core installation which has "load average: 1.09, 1.06, 1.11", so it would definitely make things smoother. 

Also we are going to release (today or tomorrow) a version with longer (and configurable) revalidation periods, I should help tuning CPU utilisation. 

The reason for this problem is that recently RPKI experiences a big uptake and repositories grow very quickly, so it's hard to catch up with the growth.

**Comment by dostalradim** [comment]
Thank you! I am going to associate more CPU cores. Configurable revalidation periods should by useful.

**Comment by edugas** [comment]
I actually had the same issue about a week ago running the latest version at the time. I added 32 cores to the VM and it ended up taking all the resources on the host.

I decided to migrate to another validator for the time being...

**Comment by lolepezy** [comment]
@edugas This is very interesting. We know it's pretty CPU-intense, but never though it doing something crazy like eating up 32-core machine entirely. Do you still have it running somewhere? Could you send the output of 
https://validator/api/healthcheck/backgrounds
https://validator/api/xodus/tx 
if you still have it running?

**Comment by edugas** [comment]
> @edugas This is very interesting. We know it's pretty CPU-intense, but never though it doing something crazy like eating up 32-core machine entirely. Do you still have it running somewhere? Could you send the output of
> https://validator/api/healthcheck/backgrounds
> https://validator/api/xodus/tx
> if you still have it running?

Unfortunately, I deleted the VMs last week but I think it's worth mentioning that I had the same high CPU usage on two separate VMs, both running up to date CentOS 8/packages. Both running on 32-core, 16GB of RAM and 32GB of space. I was running validator/rtr version 3.1-2019.10.18_12.15.36 and feeding 6 routers.

I wish I could provide more details. Maybe @dostalradim will be able to replicate the problem?

**Comment by dostalradim** [comment]
Server utilization looks good after restart. I give you message if it escalates.

**Comment by lolepezy** [comment]
We think we have found the source of the problem, it maybe a thread leak, not related to the the validation complexity. Working on the fix.

**Comment by lolepezy** [comment]
Please upgrade to the version 3.1-2019.10.29_16.55.05 both rpki-validator-3 and rpki-rtr-server (rtr server has small some memory optimisations), the problem should be resolved.

**Comment by dostalradim** [comment]
![Snímek obrazovky 2019-11-06 v 7 46 58](https://user-images.githubusercontent.com/9046924/68274535-be26c780-0069-11ea-9233-ece1a53b72a5.png)

First peak is previous version and next one is new version.

Thank you for fast solution!

**Comment by lolepezy** [comment]
@dostalradim Thanks for reporting and data!
