### ISSUE TITLE
docker RPKI validator 3 - using api can not create an valid api call 

### ISSUE THREAD

**Issue by partuner** [RIPE-NCC/rpki-validator-3#115]
Hi ,

i installed the rpki validaor 3 based on docker centos7 and trying to make api GET as using in yot documentation but with no success , 
for example when do :
curl http://localhost:8080/api/v1/validity/AS12654/93.175.146.0/2
i am getting the following error:
  "timestamp" : "2019-11-13 02:58:07",
  "status" : 406,
  "error" : "Not Acceptable",
  "message" : "Could not find acceptable representation",
  "path" : "/api/v1/validity/AS12654/93.175.146.0/2"

please help.
what iam doing worng ?

**Comment by lolepezy** [comment]
Hi, 

You can use validator's API through this:

curl -X GET --header 'Accept: application/json' 'https://localhost:8080/api/bgp/validity?prefix=93.175.146.0%2F24&asn=AS12654' (also I assume that you meant 93.175.146.0/24).

You can explore the API here https://rpki-validator.ripe.net/swagger-ui.html with a browser (or the same way on "http://localhost:8080/swagger-ui.html").

**Comment by partuner** [comment]
this is the error iam getting now when using the cli api curl:
trying :
curl -X GET --header 'Accept: application/json' 'https://localhost:8080/api/bgp/validity?prefix=93.175.146.0%2F24&asn=AS12654'
result:
 error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by partuner** [comment]
ok found the problem sorry , i was using https in your example , with http its working.
thank you very much

**Comment by lolepezy** [comment]
You are trying to connect using HTTPS, but locally validator supports only plain HTTP. So just replace with http://localhost...
