### ISSUE TITLE
Different versions of the database?

### ISSUE THREAD

**Issue by racompton** [RIPE-NCC/rpki-validator-3#117]
Hi, sorry this is not an issue but I didn't know where else to ask this question.  
What happens if the routers are communicating to two separate instances of the validator software and one of them loses connectivity to the Internet and doesn't have a complete list of ROAs.  
Will the routers pull from both validators and then get a complete list of valid/invalid ROAs or will the routers only keep a copy of one of the validators' list of ROAs and it could be the validator with an incomplete list or the one with a complete list?
If this is the incorrect place to ask this question, please let me know where would be more appropriate.   Thanks!

**Comment by lolepezy** [comment]
Hi Rich,

Unfortunately, we don't really know the answer to this question as it depends on the logic of the router much more than logic of the validator. I assume that you can have any possible strange corner cases in case of multiple caches and I think you should refer to the documentation of the router RPKI cache or maybe ask their support.

For example, I could find something like this:
https://www.juniper.net/documentation/en_US/release-independent/solutions/information-products/pathway-pages/bgp-rpki-tn.pdf

But it just says "Routers support multiple RPKI validator sessions and in this way avoid single
points of failure of device or communications link. Routers also support preference settings for which ROA to use if a conflict occurs between caches."

Hope that helps.

**Comment by racompton** [comment]
Thanks for the reply.  I figured it was up to the router how to handle this.  From what I've seen, Nokia and Cisco IOS-XR don't have the option for a preference but I've sent them both a feature request.
