### ISSUE TITLE
SSL fails to unwrap RRDP due to a buffer size issue

### ISSUE THREAD

**Issue by geeohgeegeeoh** [RIPE-NCC/rpki-validator-3#118]
Error retrieving RRDP repository at https://rrdp.rpki.nlnetlabs.nl/rrdp/notification.xml: Error downloading 'https://rrdp.rpki.nlnetlabs.nl/rrdp/0d247cb5-01a6-4c1c-a272-ef55c6a65362/2/snapshot.xml', cause: failed reading response stream for https://rrdp.rpki.nlnetlabs.nl/rrdp/0d247cb5-01a6-4c1c-a272-ef55c6a65362/2/snapshot.xml: java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Fail to unwrap network record, cause: javax.net.ssl.SSLException: Fail to unwrap network record, cause: Fail to unwrap network record, cause: javax.crypto.ShortBufferException: Output buffer too small, cause: Output buffer too small

FreeBSD 12.1, with openjdk 12 2019-07-16

**Comment by geeohgeegeeoh** [comment]
Looks like its a known OpenJDK bug. You probably could hack around it, but the root cause is not in you: its OpenJDK

**Comment by geeohgeegeeoh** [comment]
problem not present on FreeBSD 12 with OpenJDK 13.

**Comment by omuravskiy** [comment]
Hi George,

I would just stick to OpenJDK 8 for our validator. Unless you need 12 or 13 for something else on that box...

Oleg

**Comment by geeohgeegeeoh** [comment]
There are a huge number of patches in network and security related areas
after eight. Thirteen is working well for me.

G
