### ISSUE TITLE
RTR-Server: Error PDU as response to an Error pdu

### ISSUE THREAD

**Issue by mroethke** [RIPE-NCC/rpki-validator-3#12]
During testing with rtrlib I noticed that the rtr-server send an error pdu as response to an error pdu. In this case it was send because the `Length of Error Text` field was invalid.
From The RFC:

> An Error Report PDU MUST NOT be sent for an Error Report PDU.  If an
   erroneous Error Report PDU is received, the session SHOULD be
   dropped.

I captured the hole session in wireshark I can upload that if necessary.

**Comment by erikrozendaal** [comment]
Thanks! I believe this is now fixed.
