### ISSUE TITLE
setting rpki-validator-3 behind a proxy

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#123]
Would anyone have the experience about the setting of the  rpki-validator-3 ? Thanks a lot.

**Comment by wibisono** [comment]
Do you have any specific questions about setting up behind proxy? We have some documentation about it:
https://github.com/RIPE-NCC/rpki-validator-3/wiki/Run-the-RPKI-Validator-behind-an-apache-proxy
https://github.com/RIPE-NCC/rpki-validator-3/wiki/Run-the-RPKI-Validator-behind-an-nginx-proxy

**Comment by JC-ZI** [comment]
HI, THANKS. may I know the Vaildator side setting?
we are using squid proxy

**Comment by JC-ZI** [comment]
Can't access.... but we can see the traffic through the proxy. 
![image006](https://user-images.githubusercontent.com/59159878/71349682-8dafd400-25aa-11ea-86f2-4234b0fd4990.png)

**Comment by omuravskiy** [comment]
For **rsync** connections you need to set the **RSYNC_PROXY** environment variable, either in the system startup script, or in a shell before starting the validator, with something like:

    export RSYNC_PROXY=myproxy:3128

For **RRDP** you have to configure proxy in the `validator.conf`:

    rpki.validator.http.proxy.host=proxy host
    rpki.validator.http.proxy.port=proxy port

**Comment by JC-ZI** [comment]
Dear Support,

For *rsync* connections you need to set the *RSYNC_PROXY* environment
variable, either in the system startup script, or in a shell before
starting the validator, with something like:

export RSYNC_PROXY=myproxy:3128


<-- I think this is my case. please find the details below:

1. Can't sync:

[image: Screenshot 2019-12-27 at 10.51.12 AM.png]
[image: Screenshot 2019-12-27 at 10.50.38 AM.png]

2. added the following on the /etc/environment

[image: Screenshot 2019-12-27 at 10.54.01 AM.png]

3. added the following setting into rpki-validator-3.sh
[image: Screenshot 2019-12-27 at 10.57.42 AM.png]

4. the problem is insist and we observed the 443 traffic of the
validator can't pass to the proxy.

Thanks a lot.


Oleg Muravskiy <notifications@github.com> 於 2019年12月23日 週一 下午11:18寫道：

**Comment by JC-ZI** [comment]
Dear Support,

For *rsync* connections you need to set the *RSYNC_PROXY* environment
variable, either in the system startup script, or in a shell before
starting the validator, with something like:

export RSYNC_PROXY=myproxy:3128


<-- I think this is my case. please find the details below:

1. Can't sync:

[image: Screenshot 2019-12-27 at 10.51.12 AM.png]
[image: Screenshot 2019-12-27 at 10.50.38 AM.png]

2. added the following on the /etc/environment

[image: Screenshot 2019-12-27 at 10.54.01 AM.png]

3. added the following setting into rpki-validator-3.sh
[image: Screenshot 2019-12-27 at 10.57.42 AM.png]

4. the problem is insist and we observed the 443 traffic of the
validator can't pass to the proxy.

Thanks a lot.


Adianto Wibisono <notifications@github.com> 於 2019年12月23日 週一 下午4:49寫道：

**Comment by JC-ZI** [comment]
Dear Support,

For *rsync* connections you need to set the *RSYNC_PROXY* environment
variable, either in the system startup script, or in a shell before
starting the validator, with something like:

export RSYNC_PROXY=myproxy:3128


<-- I think this is my case. please find the details below:
1. Can't sync:
![Screenshot 2019-12-27 at 10 51 12 AM](https://user-images.githubusercontent.com/59159878/71499388-399f3b00-289b-11ea-8813-0ded5648c19e.png)
![Screenshot 2019-12-27 at 10 50 38 AM](https://user-images.githubusercontent.com/59159878/71499395-3efc8580-289b-11ea-9a4c-c6132fd22531.png)

2. added the following on the /etc/environment
![Screenshot 2019-12-27 at 10 54 01 AM](https://user-images.githubusercontent.com/59159878/71499405-4b80de00-289b-11ea-92ca-b7bf76309c4b.png)

3. added the following setting into rpki-validator-3.sh
![Screenshot 2019-12-27 at 10 57 42 AM](https://user-images.githubusercontent.com/59159878/71499423-59cefa00-289b-11ea-8020-0646c2f8c9f9.png)

4. the problem is insist and we observed the 443 traffic of the
validator can't pass to the proxy.

**Comment by omuravskiy** [comment]
Are you running your proxy on a host that has a hostname **myproxy**?
If not, you should change **myproxy** to a proper host name, probably even fully-qualified.

**Comment by JC-ZI** [comment]
We use a IP address.

「Oleg Muravskiy <notifications@github.com>」在 2019年12月27日 週五，下午6:33 寫道：

**Comment by JC-ZI** [comment]
Would you please give us the completed and useful steps?

「Oleg Muravskiy <notifications@github.com>」在 2019年12月27日 週五，下午6:33 寫道：

**Comment by omuravskiy** [comment]
Well, we can't provide complete steps to everybody, because everybody would have different settings. I provided you an example, you have to use **your** proxy hostname or  IP address in place of **myproxy**.
I hope this is still useful.

**Comment by JC-ZI** [comment]
Hi as mentioned, we use a IP address.

「Oleg Muravskiy <notifications@github.com>」在 2019年12月27日 週五，下午11:12 寫道：

**Comment by JC-ZI** [comment]
Hi as mentioned, we use a IP address.
Please advise.

「Oleg Muravskiy <notifications@github.com>」在 2019年12月27日 週五，下午11:12 寫道：

**Comment by omuravskiy** [comment]
Well, I do not know IP address of your proxy, so I can't give you more specific instructions.

Let's try this: in a terminal on the server where you run rpki-validator, type these 2 commands:
```
export RSYNC_PROXY=<proxy_ip>:<proxy_port>
rsync rsync://rpki.ripe.net/
```
(please replace **<proxy_ip>** and **<proxy_port>** by the values appropriate in your setup).

Do you see a reply from our server, or an error?

**Comment by JC-ZI** [comment]
It is just a ipv4 private IP address.


export RSYNC_PROXY=10.10.183.x:3128

Has posted the details and captured the log.
Thanks

「Oleg Muravskiy <notifications@github.com>」在 2019年12月27日 週五，下午11:29 寫道：

**Comment by omuravskiy** [comment]
What do you see after typing two commands I posted above?

**Comment by JC-ZI** [comment]
https://github.com/RIPE-NCC/rpki-validator-3/issues/123

Hi I read all posts from this link.

**Comment by omuravskiy** [comment]
Type these two commands:

    export RSYNC_PROXY=10.10.183.3:3128
    rsync rsync://rpki.ripe.net/

What do you see?

**Comment by JC-ZI** [comment]
Hi may try it when I am back to the office.
Thanks.

**Comment by job** [comment]
@JC-ZI  Are you using a `SOCKS` proxy for the `rsync` program to connect through? I don't think that the `rsync` program can use a `HTTP` proxy to connect to the outside world.

**Comment by JC-ZI** [comment]
> @JC-ZI Are you using a `SOCKS` proxy for the `rsync` program to connect through? I don't think that the `rsync` program can use a `HTTP` proxy to connect to the outside world.

Thanks a lot Job

**Comment by JC-ZI** [comment]
> Type these two commands:
> 
> ```
> export RSYNC_PROXY=10.10.183.3:3128
> rsync rsync://rpki.ripe.net/
> ```
> 
> What do you see?

![Screenshot 2019-12-30 at 9 45 46 AM](https://user-images.githubusercontent.com/59159878/71565393-6a74af80-2ae9-11ea-89f2-e8b816cd4616.png)

**Comment by omuravskiy** [comment]
This error means that your proxy setup is not working. It is not related to the rpki-validator setup.

You need to fix your proxy setup first. When it works, you should not see an error from the `rsync rsync://rpki.ripe.net/` command, you should see the response from our server.

Some suggestions for setting up your proxy are here: https://superuser.com/questions/87827/how-to-force-the-rsync-to-use-my-proxy-settings

**Comment by JC-ZI** [comment]
> This error means that your proxy setup is not working. It is not related to the rpki-validator setup.
> 
> You need to fix your proxy setup first. When it works, you should not see an error from the `rsync rsync://rpki.ripe.net/` command, you should see the response from our server.
> 
> Some suggestions for setting up your proxy are here: https://superuser.com/questions/87827/how-to-force-the-rsync-to-use-my-proxy-settings

**Comment by JC-ZI** [comment]
> This error means that your proxy setup is not working. It is not related to the rpki-validator setup.
> 
> You need to fix your proxy setup first. When it works, you should not see an error from the `rsync rsync://rpki.ripe.net/` command, you should see the response from our server.
> 
> Some suggestions for setting up your proxy are here: https://superuser.com/questions/87827/how-to-force-the-rsync-to-use-my-proxy-settings

Thanks for information. Will try it.

**Comment by JC-ZI** [comment]
There is error when we run the command ./rpki-validator-3.sh run
![Screenshot 2020-01-02 at 3 25 39 PM](https://user-images.githubusercontent.com/59159878/71655958-51336380-2d74-11ea-949f-fd08238e37ba.png)

**Comment by JC-ZI** [comment]
Hi would you please advice if I am wrong to set up. 
Please Clarify, there is many errors even I followed up the steps.

**Comment by JC-ZI** [comment]
Hi any update? Thanks

**Comment by lolepezy** [comment]
Hi,

The link you have pointed to 

says that you need to start the validator using
sudo systemctl start rpki-validator-3
please try that. You are having all these troubles with paths because you are trying to run it manually. 

But if you really have to run it manually, you will need to set up the same environment variables as set in the /etc/systemd/system/rpki-validator-3.service:

JAVA_CMD=/usr/bin/java
CONFIG_DIR=/etc/rpki-validator-3
JAR=/usr/lib/rpki-validator-3.jar

**Comment by JC-ZI** [comment]
Thanks a lot. 

So if using “sudo systemctl start rpki-validator-3” , then no need to update the path.

Sec, if I edit the paths manually, can We still run  “sudo systemctl start rpki-validator-3” normally?
If not, It would be better to keep running “ sudo systemctl start rpki-validator-3” and don’t edit those path manually?
Thanks

**Comment by jbacker** [comment]
Given you would export the same environment variables as would be used when using systemctl, that shouldn't give problems. Is there any reason why you can't just use the systemd service?

I assume the screenshot is still from attempting to run this without exporting the environment variables as mentioned before, and thus the required config cannot be found.

**Comment by JC-ZI** [comment]
> Given you would export the same environment variables as would be used when using systemctl, that shouldn't give problems. Is there any reason why you can't just use the systemd service?<— yes. Agree.
> 
> I assume the screenshot is still from attempting to run this without exporting the environment variables as mentioned before, and thus the required config cannot be found.<— then this problem will be also solved when using systemd service. Am I correct? 

Thanks.

**Comment by lolepezy** [comment]
Sorry for the late reply.

> then this problem will be also solved when using systemd service. Am I correct?

Yes, but in this case you will need add the "Environment=RSYNC_PROXY=10.10.183.3:3128" in the /etc/systemd/system/rpki-validator-3.service

Do you still have the issue?

**Comment by JC-ZI** [comment]
> Sorry for the late reply.
> 
> > then this problem will be also solved when using systemd service. Am I correct?
> 
> Yes, but in this case you will need add the "Environment=RSYNC_PROXY=10.10.183.3:3128" in the /etc/systemd/system/rpki-validator-3.service
> 
> Do you still have the issue?

Dear lolepezy,
The issue is not solved.  

 Yes, but in this case you will need add the "Environment=RSYNC_PROXY=10.10.183.3:3128" in the /etc/systemd/system/rpki-validator-3.service <-- Thanks for your advise. just added. The result is still failed.

Please find the error for your comments.
![Screenshot 2020-01-09 at 2 36 55 PM](https://user-images.githubusercontent.com/59159878/72043956-84826f00-32ed-11ea-945d-88375b2c99cf.png)

on the other hand, we are checking the firewall rules. Thanks.

**Comment by lolepezy** [comment]
I would advice to check if your rsync connection works in principle before setting up anything in the validator. Did you try to execute this?
```
export RSYNC_PROXY=10.10.183.3:3128
rsync -l rsync://rpki.ripe.net/repository
```
? Did you get a list of the repository content? If rsync command doesn't work with your proxy, the validator will not work, because it uses the same rsync command.

Secondly, if you have http/https proxy, I would advice to make sure it works before setting anything up in the validator. Try this script
```
export ALL_PROXY=<your_http_proxy_ip>:<your_http_proxy_port>
curl https://rrdp.ripe.net/notification.xml
```
if it doesn't print back some XML, you need to fix the proxy setup first. 

We have added a wiki page about proxy setup
https://github.com/RIPE-NCC/rpki-validator-3/wiki/Running-the-RPKI-Validator-behind-an-HTTP-and-Rsync-proxy
I hope it's helpful.

**Comment by JC-ZI** [comment]
Thank you for the advices and Please find the result below:
#export RSYNC_PROXY=10.10.x.x:3128
#rsync -l rsync://rpki.ripe.net/repository
The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

drwxr-xr-x        135,168 2019/10/28 20:54:41 .
-rw-r--r--          1,259 2019/10/28 20:54:41 2a7dd1d787d793e4c8af56e197d4eed92af6ba13.cer
-rw-r--r--            490 2019/10/28 20:54:41 ripe-ncc-ta.crl
-rw-r--r--          1,796 2019/10/28 20:54:41 ripe-ncc-ta.mft
drwxrwxr-x      1,409,024 2020/01/13 12:01:31 DEFAULT
drwxrwxr-x          4,096 2020/01/13 12:02:53 aca

=======================================
export ALL_PROXY=10.10.x.x:3128
curl https://rrdp.ripe.net/notification.xml
sample result:
<delta serial="21" uri="https://rrdp.ripe.net/ab2b0a90-4c5b-47e3-aaf1-8133029df265/21/delta.xml" hash="96E20F7E7CE5E3FC7AF6AE2418AA65738235FCED8F8EBFE20CE6E224747F9E07"/><delta serial="20" uri="https://rrdp.ripe.net/ab2b0a90-4c5b-47e3-aaf1-8133029df265/20/delta.xml" hash="7A0FF5E5A2DBC47D6735714E203B70E92EB7CC121D70440ABB24ACA335CAE37A"/>

**Comment by lolepezy** [comment]
Hi, 

We have issued release 3.1-2020.01.13.09.31.26 to address the rsync proxy issue. Not you can set rsync and http proxy in the application.properties file. It is now as simple as it can get. Please see the https://github.com/RIPE-NCC/rpki-validator-3/wiki/Running-the-RPKI-Validator-behind-an-HTTP-and-Rsync-proxy

I your case, I believe, you need to add
rpki.validator.http.proxy.host=10.10.x.x
rpki.validator.http.proxy.port=3128
rpki.validator.rsync.proxy.host=10.10.x.x
rpki.validator.rsync.proxy.port=3128

What type of proxy do you use?

**Comment by JC-ZI** [comment]
> Hi,
> 
> We have issued release 3.1-2020.01.13.09.31.26 to address the rsync proxy issue. Not you can set rsync and http proxy in the application.properties file. It is now as simple as it can get. Please see the https://github.com/RIPE-NCC/rpki-validator-3/wiki/Running-the-RPKI-Validator-behind-an-HTTP-and-Rsync-proxy
> 
> I your case, I believe, you need to add
> rpki.validator.http.proxy.host=10.10.x.x
> rpki.validator.http.proxy.port=3128
> rpki.validator.rsync.proxy.host=10.10.x.x
> rpki.validator.rsync.proxy.port=3128
> 
> What type of proxy do you use?
we are using the squid proxy.

**Thanks a lot for the ref link below and you all support.**
**Now, Can get the items normally.**

On other the hand, we found that there two IP address below on the firewall. 
Are these two IP address/servers official? and Do we need to permit these IP with a 873 port? Thanks.

Name:    rpki-repository.nic.ad.jp
Address:  192.41.192.216
Name:    rpki-repo.registro.br
Address:  200.160.2.50

**Comment by lolepezy** [comment]
> Name: rpki-repository.nic.ad.jp
> Address: 192.41.192.216
> Name: rpki-repo.registro.br
> Address: 200.160.2.50

Yes, they are official, they are a part of APNIC RPKI hierarchy, you would need to allow connection to them to get the full RPKI data set.

> Do we need to permit these IP with a 873 port?
If you use rsync proxy, you don't need to do that, rsync will use your proxy to access every URL.

**Comment by JC-ZI** [comment]
> > Name: rpki-repository.nic.ad.jp
> > Address: 192.41.192.216
> > Name: rpki-repo.registro.br
> > Address: 200.160.2.50
> 
> Yes, they are official, they are a part of APNIC and LACNIC RPKI hierarchies, you would need to allow connection to them to get the full RPKI data set.
> 
> > Do we need to permit these IP with a 873 port?
> 
> If you use rsync proxy, you don't need to do that, rsync will use your proxy to access every URL.

Coz there is a firewall in our environment so we need to open these ports on the firewall? Thanks.

**Comment by lolepezy** [comment]
Yes, you will need to open 873 to access these repositories.

**Comment by JC-ZI** [comment]
> Yes, you will need to open 873 to access these repositories.

Thanks for you all support.
