### ISSUE TITLE
Juniper instability after upgrading to version 3.1

### ISSUE THREAD

**Issue by CFLagerfeldt** [RIPE-NCC/rpki-validator-3#124]
After upgrading to validator 3.1 we see stability issues on Juniper routers. If the validator is restarted (rtr service is kept running), the Juniper routers will refresh some (a lot but not all) validated routes in it's RIB, often triggering dampening. This behavior was not seen prior to version 3.1.

After looking through the commits, could it be that this is caused by the changes related to serial propagation from manifest in a88ec13f84b889f88f74a578f65256443fa05967? The serial number pushed in the RTR PDUs could possibly cause big integer issues?

(previous running version 3.0-407)

**Comment by lolepezy** [comment]
Hi,

Did you try to restart the RTR server as well? Maybe that would help.

Generally, the reset procedure would be
- stop the validator
- delete all the *.xd files in /var/lib/rpki-validator-3/db
- start it again and wait a few minutes until all the trust anchors are ready.

In principle, you don't have to stop RTR server while doing this with the validator, to minimise downtime, but I would recommend to restart it right after. Hope that helps.

Also, the commit you pointed out is related to how we chose "the latest" manifest, there was a bug in this logic. This serial number/manifest number doesn't propagate to RTR in any way, so I don't think it could be a reason for RTR issues.

**Comment by CFLagerfeldt** [comment]
Our restart script looks exactly like your proposed procedure. Question then is what has changed in the RTR server between the two versions? The RTR server has been restarted as well, but the issue is still seen when restarting the validation server.

What we've done now to test things is I have setup GoRTR in paralell on the same VM listening on another port. It's setup to use the RIPE v3 generated export.json output as it's source. No issue is seen on the Juniper routers connecting to that.

**Comment by lolepezy** [comment]
Hm, 

> Question then is what has changed in the RTR server between the two versions?

Version 407 is pretty old and there's been a lot of changes in the validator but nothing functional has been changed in the RTR server, and even then it was a change reducing internal lock contention.

Do you have anything suspicious in the logs? 
sudo journalctl  -u rpki-rtr-server
or
something in /var/log/messages ?

Can you try changing "logging.level.net.ripe.rpki.rtr=WARN" to "logging.level.net.ripe.rpki.rtr=DEBUG" in the /etc/rpki-rtr-server/application.properties and see if it complain to logs?

**Comment by lolepezy** [comment]
Which router model/version do you have? If we can get a virtual one from Juniper, it would be good to know what to emulate.

**Comment by lolepezy** [comment]
Another assumption -- it can be that due to gradual growth of the number of prefixes, rtr-server doesn't have enough memory anymore. Could you change "jvm.memory.maximum=128m" to  "jvm.memory.maximum=256m" in /etc/rpki-rtr-server/application.properties, restart it and see if it helps?

**Comment by CFLagerfeldt** [comment]
The logs did not contain anything interesting with the defualt logging level set to WARN. I changed it to DEBUG and [here](https://gist.github.com/CFLagerfeldt/49dafcea3bafe0ec1df469c7ef2001ba) is an extract of what's seen during/after the reload of the validation daemon.

- We've been running the RTR daemon with jvm.memory.initial=4096m and jvm.memory.maximum=4096m since we started using it.

- We've tested and seen the issue on Junos 15.1F6, 17.3R3 and 17.4R2.

**Comment by lolepezy** [comment]
That doesn't look right. Does anywhere in the log it says
"fetched NNN validated roa prefixes from http://localhost:8080/api/objects/validated"?

Because what we can say from this piece of log is that it cannot update its cache.
What does https://localhost:8080/api/healthcheck say? Are there exception stack traces in the validator's log?

**Comment by CFLagerfeldt** [comment]
[rtr-log_20200103_01.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4019406/rtr-log_20200103_01.txt)
[rtr-log_20200103_11.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4019407/rtr-log_20200103_11.txt)

curl http://localhost:8080/api/healthcheck 
{
  "data" : {
    "overalStatus" : "OK",
    "trustAnchorReady" : [ {
      "taName" : "AfriNIC RPKI Root",
      "complete" : true
    }, {
      "taName" : "APNIC RPKI Root",
      "complete" : true
    }, {
      "taName" : "ARIN",
      "complete" : true
    }, {
      "taName" : "LACNIC RPKI Root",
      "complete" : true
    }, {
      "taName" : "RIPE NCC RPKI Root",
      "complete" : true
    } ],
    "bgpDumpReady" : {
      "https://www.ris.ripe.net/dumps/riswhoisdump.IPv6.gz" : true,
      "https://www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz" : true
    },
    "databaseStatus" : {
      "READONLY_TRANSACTIONS" : "1636015",
      "DISK_USAGE" : "1250232058",
      "BYTES_WRITTEN" : "7078163270",
      "FLUSHED_TRANSACTIONS" : "39461",
      "ACTIVE_TRANSACTIONS" : "1",
      "BYTES_MOVED_BY_GC" : "262777882",
      "BYTES_READ" : "286141644800",
      "TRANSACTIONS" : "573625",
      "UTILIZATION_PERCENT" : "50"
    },
    "buildInformation" : {
      "version" : "3.1-2019.12.16.15.18.18"
    }
  }
}

Attaching complete logs. _01 is from this morning and is the one I extracted from earlier. _11 is from midday and shows the same issue, but when the validator's database was not cleared during the restart.

**Comment by lolepezy** [comment]
I see one clue there:

rtr-log_20200103_11.txt:Jan  3 11:43:14 s-fre-rpki1 rpki-rtr-server.sh: 2020-01-03 11:43:14.477  INFO 39338 --- [eduler_Worker-3] n.r.r.r.a.v.RefreshCacheController       : fetched 124323 validated roa prefixes from http://localhost:8080/api/objects/validated
rtr-log_20200103_11.txt:Jan  3 11:44:43 s-fre-rpki1 rpki-rtr-server.sh: 2020-01-03 11:44:43.223  INFO 39338 --- [eduler_Worker-5] n.r.r.r.a.v.RefreshCacheController       : fetched 33684 validated roa prefixes from http://localhost:8080/api/objects/validated
rtr-log_20200103_11.txt:Jan  3 11:49:14 s-fre-rpki1 rpki-rtr-server.sh: 2020-01-03 11:49:14.336  INFO 39338 --- [eduler_Worker-2] n.r.r.r.a.v.RefreshCacheController       : fetched 124323 validated roa prefixes from http://localhost:8080/api/objects/validated

So you have log for the validator between 2020-01-03 11:43 and 2020-01-03 11:49? This drop in the amount of prefixes could explain the behaviour.

**Comment by CFLagerfeldt** [comment]
[validator-log_20200103_11.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4019599/validator-log_20200103_11.txt)
Doesn't say much since it has only been running with logging level set to WARN. Changed it now to DEBUG. Will send you a new file tomorrow for both.

**Comment by lolepezy** [comment]
Thanks. 
So It seems was a validator restart after all.

**Comment by lolepezy** [comment]
Just to make sure: you have also upgraded the rtr-server together with validator, right? So they both are at version "3.1-2019.12.16.15.18.18"?

**Comment by CFLagerfeldt** [comment]
[validator-log_20200106_12.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4026013/validator-log_20200106_12.txt)
[validator-log_20200105_11.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4026014/validator-log_20200105_11.txt)
[rtr-log_20200106_12.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4026015/rtr-log_20200106_12.txt)
[rtr-log_20200105_11.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/4026016/rtr-log_20200105_11.txt)

Please see attached debug logs from the most recent tests. Both validator and RTR are running the same version. I have a pcap file showing the communication between the server and one Juniper router. Since the capture may contain sensitive information I'll send it to you directly.

Note. The validator daemon was restarted at 2020-01-06 12:13:47 UTC.
Note. The validator was restarted without clearing/deleting the .xd database files.
Note. The first four (4) packets in the pcap is from last delta PDU before the restart of the validator.

**Comment by lolepezy** [comment]
Thanks, we are looking into it. 

1) You don't have to restart validator that often -- it's much more stable now and works pretty much without problems. So you don't have to go through these troubles restarting it.

2) We are working on a change to address your issue, will release a version for you to try today or tomorrow.

**Comment by lolepezy** [comment]
Hi,

We have released the version rpki-validator-3.1-2020.01.07.14.37.29 (and the same for rtr-server). It is addressing the issue with the amount of prefixes dropping because of the validator restart. Please upgrade and let us know if you still experience problems (I hope not).

**Comment by CFLagerfeldt** [comment]
Unfortunately I don't see any change in behavior with the new version. I have in parallel opened a case with Juniper for them to investigate the behavior on the router. I see this as two separate things, behavior change in the validator causing unexpected behavior on the router.

**Comment by lolepezy** [comment]
Do you have logs for some period after the upgrade? It would be very useful to see if there are still these dips in the number of prefixes.

**Comment by CFLagerfeldt** [comment]
Sorry for the slow response. Last week we started seeing intermittent issues with CPU exhaustion and decided to stop using the RIPE validator. Those issues were not necessarily related to the new version and could be to us running it with debug output active over an extended period of time.

Juniper is continuing investigation related to the dampening in PR1483097.

**Comment by lolepezy** [comment]
Closing the issue as it seems to be not the problem with the validator.
