### ISSUE TITLE
Tests fail on JDK 11 because Instant has nanoseconds

### ISSUE THREAD

**Issue by ties** [RIPE-NCC/rpki-validator-3#129]
The test suite for this project fails on JDK 11, likely due to a change in Instant in JDK 9.

The root cause seems to be that `Instant`s now have nanosecond precision, while the encoder that encodes Instants as bytes only considers the milliseconds since the epoch.

https://github.com/RIPE-NCC/rpki-validator-3/blob/e77bfa8656422b4a62d1d08af62931e8e5d129b2/rpki-validator/src/main/java/net/ripe/rpki/validator3/storage/encoding/custom/Coders.java#L51

While fixing this (by appending the nanoseconds) is easy, this will cause issues when the time since epoch no longer fits in a 64 bit number.

**Comment by lolepezy** [comment]
1) We only care about milli-seconds, actually maybe even just the seconds
2) We want whatever we serialise to be the same across different versions of JDKs
So ideally we weed some sort of portable way to extract milliseconds and that would be enough for all purposes.

**Comment by ties** [comment]
>     1. We only care about milli-seconds, actually maybe even just the seconds

I think agree with that. However this may break some assumptions that a user of the API expects ("the time I pass in is the time that is set"). In addition you needs to be applied for every place where an Instant is passed in – so this is prone to mistakes.

>     2. We want whatever we serialise to be the same across different versions of JDKs
>        So ideally we weed some sort of portable way to extract milliseconds and that would be enough for all purposes.

We have this right now. However this breaks some tests (because `Instant.now()` that is passed in has the nanoseconds.

We can extract the nanoseconds separately and append that to the stored value. We can then switch how it is deserialized ("old format") or ("millis + separate nanos") depending on the length.
