### ISSUE TITLE
rpki validator not getting objects from LACNIC  and AfriNIC 

### ISSUE THREAD

**Issue by partuner** [RIPE-NCC/rpki-validator-3#146]
dear Team ,

i have a problem in my rpki server validor , all was fine until the last day , i cannot get any objects for LACNIC RPKI and for AfriNIC RPKI :
dont understand the error messgae
example:
![error](https://user-images.githubusercontent.com/29863514/75421721-91156200-5943-11ea-88d1-0399d0e0f139.PNG)

what can be the problem for that?
please advice

**Comment by ties** [comment]
What build are you using?

Can you run rsync to the lacnic repository successfully from the machine? i.e.:
```
$ rsync rsync://repository.lacnic.net/rpki/lacnic/rta-lacnic-rpki.cer .
```

**Comment by partuner** [comment]
i cannot run the command successfully , iam getting the same error : 
![image](https://user-images.githubusercontent.com/29863514/75434752-b19ce680-595a-11ea-88ad-ac71386db555.png)

from what reason it could be ? 

and iam using the Docket image rpki-validator-3 on centos7 operation system

**Comment by partuner** [comment]
i found the problem , regarding the log i sent you it is looks like the problem was in my firewall , now its working , thank you.

iam closing the ticket.
