### ISSUE TITLE
Please fix comment in conf/application.properties

### ISSUE THREAD

**Issue by maelmans** [RIPE-NCC/rpki-validator-3#166]
In conf/application.properties it is described that "By default the validator will listen on localhost ONLY" which is a good thing.
However it also states "You can change this behavior by uncommenting the following line".

This line however is already uncommented and should be commented out if one wants to change the behavior.

Hence I would like to propose to change:
"You can change this behavior by uncommenting the following line"
to
"You can change this behavior by commenting out the following line"

Thanks

**Comment by wibisono** [comment]
Thank you for the correction, we'll incorporate this change on the next release that we will have soon.

**Comment by maelmans** [comment]
Thanks Adianto!

**Comment by lolepezy** [comment]
Fixed in the version 3.1-2020.05.08.09.26.49 that we just released.
