### ISSUE TITLE
Systemd service file is marked executable

### ISSUE THREAD

**Issue by AguirreIF** [RIPE-NCC/rpki-validator-3#167]
Hi, I have the RPKI validator and RTR server installed on a GNU/Linux Debian 10 machine:

```
ii  rpki-rtr-server                 3.1.2020.03.16.13.34.48
ii  rpki-validator-3                3.1.2020.03.16.13.34.48
```
and get the following messages in ``/var/log/syslog``:

```
Apr  4 06:31:02 rpki systemd[1]: Configuration file /etc/systemd/system/rpki-validator-3.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Apr  4 06:31:02 rpki systemd[1]: Configuration file /etc/systemd/system/rpki-rtr-server.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

Should I remove the execution bit?

Regards,

**Comment by ties** [comment]
Hi,

That sounds like it would be the fix.

What release did you install? I will try to make sure we re-publish one next week.

**Comment by AguirreIF** [comment]
Hi,

I installed the [rpki-rtr-server-3.1-2020.03.16.13.34.48.deb](https://ftp.ripe.net/tools/rpki/validator3/rc/deb/rpki-rtr-server-3.1-2020.03.16.13.34.48.deb) and [rpki-validator-3.1-2020.03.16.13.34.48.deb](https://ftp.ripe.net/tools/rpki/validator3/rc/deb/rpki-validator-3.1-2020.03.16.13.34.48.deb) packages.

Regards,

**Comment by ties** [comment]
I could reproduce the issue (for rc and prod). Thanks your for reporting the issue.

The files are not executable in the repo, I will take a look tomorrow.

In the meanwhile I do not recommend the current RC due to issues you may experience with SSL handshakes. The production build does not have this issue.

**Comment by ties** [comment]
Thanks for reporting the issue. It should be fixed in the latest beta and rc.

If you have any further questions please let me know 👍

**Comment by AguirreIF** [comment]
> Thanks for reporting the issue. It should be fixed in the latest beta and rc.
> 
> If you have any further questions please let me know +1

Great, thanks very much.

I'm using the RC because I was having issues (couldn't connect to the RTR server) with the prod release.

Regards,
