### ISSUE TITLE
Can not upload apnic as0 tal

### ISSUE THREAD

**Issue by ties** [RIPE-NCC/rpki-validator-3#180]
I got the following error while adding the APnic AS0 tal. This gets added fine when adding it to `preconfigured-tals` before starting:

```
$ ./upload-tal.sh ./apnic-as0.tal http://validator.local:9176
{
  "timestamp" : "2020-04-24 12:38:08",
  "status" : 500,
  "error" : "Internal Server Error",
  "message" : "Request processing failed; nested exception is javax.validation.ConstraintViolationException: execute.command.subjectPublicKeyInfo: size must be between 100 and 2000",
  "path" : "/api/trust-anchors/upload"
}
```
```
$ cat apnic-as0.tal
ca.name = APNIC AS0 Root
certificate.location = rsync://registry-testbed.apnic.net/as0-test/ta/ta.cer
public.key.info = MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvo8wLXUFnUjXyX
hy11VpFWiDZy7Hs9TAIfymiKwCbOz3ZMp8iWgWoxI5IJzO0cIz/KaRgBbzVeXRFttp3nzh5Up+EQ
XnL3ixWh3gAjSD0mTOLchLtS4pSuuHxLfdqTreCRLVK2Fbq09jUUPf76C6TazIQouMp6epGOJZvS
fmBMK3TQphlXC/iREbiMtDL7gPhexidllhuNbk4PXXBhXxoUjOEG4YdVUC/MV3dXZ72IOtl1HQ9J
3tky/bgaDVykD4j4wqHyrzhiXQ45KIrY7JGT95Z++L00OrjxlLwZoKi5vxh9U4rDtNUhPKESzpqu
t1+cO4WX+Z6L2DR80abh1DOQIDAQAB
```

**Comment by lolepezy** [comment]
It's the ValidPublicKeyInfo annotation. Can you adjust the MAX size to something appropriate for this SPKI?

**Comment by ties** [comment]
Turns out this is because there are newlines in the `publickey.info` line.

I will see if this also fixes the public-key mismatch error.

**Comment by ties** [comment]
This also fixes the public-key mismatch error.

I guess this is caused by the copy-paste from https://www.apnic.net/community/security/resource-certification/#st-anchor

**Comment by ties** [comment]
This also fixes the public-key mismatch error.

I guess this is caused by the copy-paste from https://www.apnic.net/community/security/resource-certification/#st-anchor

**Comment by wibisono** [comment]
I don't see this requires further action, closing for now. Reopen if needed.
