### ISSUE TITLE
RTR Validator not ready yet

### ISSUE THREAD

**Issue by Fab96** [RIPE-NCC/rpki-validator-3#182]
Hi,
Why sometimes do I get this error?
`WARN 2448 --- [eduler_Worker-1] n.r.r.r.a.v.RefreshCacheController       : validator http://localhost:8080/api/objects/validated not ready yet, will retry `

I tried to delete db directory and I am using Ubuntu Desktop 18.04.3 on a virtual machine.

**Comment by lolepezy** [comment]
Hi,

This is not an error, and it's normal to see it in the logs.
Every time validator is in the process of re-validating some of the repositories/trust anchors and reports it reports "not ready". It is not an error per se, it just means that it cannot return a consistent set of asn+prefixes to the rtr-server so rtr-server will retry again after some time (by default in 1 minute).

It only becomes a problem if these message come one after another for too long, it could mean that the validator is stuck somehow and cannot proceed (which we didn't see happening, but if it still does, it's indeed a bug).
