### ISSUE TITLE
Invalid LACNIC repositories

### ISSUE THREAD

**Issue by bofh16** [RIPE-NCC/rpki-validator-3#183]
Hello,
I've been trying to get rid of a couple invalid LACNIC repositories. I engaged them for a fix and they confirmed it had been deployed. I still have them, though. On the contrary, [RIPE Validator](https://rpki-validator.ripe.net/trust-anchors/monitor/3) doesn't have them. Can you advise, if I should change anything manually in LACNIC TAL or anything else, please?

![ripe_lacnic_repos](https://user-images.githubusercontent.com/27564710/80470975-07821080-8943-11ea-9522-37d6d60f8d9f.png)
![prod_lacnic_repos](https://user-images.githubusercontent.com/27564710/80470984-0bae2e00-8943-11ea-91f9-ad7cb3758ee4.png)

**Comment by lolepezy** [comment]
Hi, Georgi

You can click on these red "ø" signs on the right and delete the repositories from your local instance. Normally broken repositories don't affect anything else, they just sit there. We don't remove them automatically as it can happen that it's a temporary situation, but if you know it's permanent, you can just remove them manually.

**Comment by bofh16** [comment]
Yes, that was silly. Thanks!
