### ISSUE TITLE
Support for optional keep-alive in TCP transport

### ISSUE THREAD

**Issue by sanjmonkey** [RIPE-NCC/rpki-validator-3#184]
It would be great to have some functionality to optionally add support for a keep-alive to be sent in TCP, at a configurable interval.

The use case being; somewhere in the path between RTR and router there is something tracking TCP sessions, and it sometimes kills them because its timers are not readily configurable and has a timeout interval < RTR refresh_interval. RTR alone often isn't chatty enough to keep sessions alive. I've seen this recently when validator rtr is a kubernetes pod and IPVS TCP timeouts default to 900s, whilst RFC8210 recommends a default of 3600s for refresh interval.

RFC8210 encourages the keep-alive behaviour;
```
   "To reduce exposure to dropped but non-terminated sessions, both
   caches and routers SHOULD enable keep-alives when available in the
   chosen transport protocol.”
```

In testing this behaviour with routers, I've implemented a stream proxy in NGINX and told it to set `so_keepalive` on the RTR listener socket. In testing, both Arista and IOS-XR respond to the TCP keep-alive as expected, and this is enough to keep IPVS from eating the sessions, and maintaining recommended RTR refresh interval of 3600s.

(also raised with routinator: https://github.com/NLnetLabs/routinator/issues/320 for reference)

**Comment by lolepezy** [comment]
We have added this to our road-map, but we can't promise it's going to be implemented any time soon. For now, closing the issue.
