### ISSUE TITLE
SLURM (Whitelisting/Blacklisting) is not honored for the /api/export.json endpoint

### ISSUE THREAD

**Issue by markusju** [RIPE-NCC/rpki-validator-3#185]
> The output will be in CSV or JSON format and consist of all validated ROAs, minus your ignore filter entries, plus your whitelist entries.

I just noticed that contrary to the statements found in the UI, the data returned from `/api/export.json` endpoint does not honor white- and/or blacklisting entries. 

SLURM is correctly processed when retrieving the data from the `/api/objects/validated` endpoint.

If this is intended behavior, I would suggest to fix the description in the frontend. If not one could clarify the functionality of the different endpoints and adjust their behavior.

Thanks! :)

**Comment by markusju** [comment]
As far as I can tell from the code, white and blacklisting is processed explicitly (and exclusively) for the `/api/objects/validated` endpoint.

This sucks, as I can't use the data produced by this endpoint for a rtr-server because the schema is not compliant with the "de-facto" standard.

Any plans to fix this?

**Comment by lolepezy** [comment]
Hi Markus,

It's a good catch and we'll going to fix it. I am inclined to add it as a separate end-point, not to break the API.

**Comment by lolepezy** [comment]
Fixed in the version 3.1-2020.05.08.09.26.49 that we just released.

**Comment by markusju** [comment]
Thanks guys, much appreciated! :)
