### ISSUE TITLE
[QUESTION] how to log the diff downloaded from the TALs

### ISSUE THREAD

**Issue by nskalis** [RIPE-NCC/rpki-validator-3#189]
Hi,

Would you be so kind to enlighten me if it is possible to log server-side the updates in ROAs ?
(that get downloaded from the TALs and communicated to the routers via the RTR server)

**Comment by ties** [comment]
The RIPE validator does not currently offer this functionality. We could add this functionality. Could you elaborate on the use case you have for this logging?

If you want to temporarily log the updates from a rtr server for debugging I would use https://github.com/cloudflare/rpki-rtr-client which saves the output retrieved from a rtr server as json.

**Comment by nskalis** [comment]
It is important in order to answer potentially answer customer complaints (PR).

On the validator, you check for the validity of a route that moment.
On a router, you can check for the validity of a route that moment (and you get also the age of that route). If a route is hidden, you can see the reason why based on the well-known extended community.

On JUNOS you can enable `traceoptions` and log something like this:
```
May  8 15:52:18.906005 rv_get_policy_state: rt 1.36.32.0/19 origin-as 1713, roa 1.36.32.0/19-19 origin-as 4760, origin-as mismatch
May  8 15:52:18.906012 rv_get_policy_state: rt 1.36.32.0/19 origin-as 1713, roa 1.36.0.0/16-16 origin-as 4760, max-length mismatch
May  8 15:52:18.906014 rv_get_policy_state: rt 1.36.32.0/19 origin-as 1713, validation result invalid
```
but this is prohibitive when the router holds the full internet routing table, is distributed problem, etc.

At this moment, a network prefix (that is invalid) has ~27% reduced visibility.
The best place to solve this is on the validator.

Logging the diff on the validator, we can see how ROAs are evolving and answer customer complaints.
