### ISSUE TITLE
jvm.mem paramaters no longer configurable in application.properties?

### ISSUE THREAD

**Issue by cwiech** [RIPE-NCC/rpki-validator-3#191]
It would seem that application.properties does not adjust the jvm memory any longer is that correct? It looks like this only takes effect if we modify the application-defaults.properties (which is probably not good form).

# grep mem application.properties 
jvm.mem.initial=4096m       # -Xms jvm option -> initial memory claimed by the jvm
jvm.mem.maximum=6244m       # -Xmx jvm option -> maximum memory for the jvm

[root@rpki1.nwr1 conf]# ps -ef | grep java
rpki     17781     1 99 16:42 ?        00:00:27 /bin/java -Xms1024m -Xmx1536m -XX:+ExitOnOutOfMemoryError -Dspring.config.location=classpath:/application.properties,file:/data/rpki-validator-latest/conf/application-defaults.properties,file:/data/rpki-validator-latest/conf/application.properties -jar /data/rpki-validator-latest/lib/rpki-validator-3.jar

**Comment by lolepezy** [comment]
Are you using the generic build?
In this case, it probably doesn't matter which config you change, it's all entirely under your control.

In the command line above the last config in the list is /data/rpki-validator-latest/conf/application.properties so it will have the highest precedence and should override the all the other jvm.mem.* values.

**Comment by cwiech** [comment]
I am using the generic build, but even though the application.properties is loaded last, it does not override the memory settings.

**Comment by lolepezy** [comment]
Hi,

We have prepared an RC version that fixes the problem
https://ftp.ripe.net/tools/rpki/validator3/rc/

We'll release it on Monday, if nothing goes wrong with it.
