### ISSUE TITLE
Upgrading Debian package rpki-rtr-server overwrites existing config file

### ISSUE THREAD

**Issue by kpostrup** [RIPE-NCC/rpki-validator-3#199]
I was upgrading from rpki-rtr-server version 3.1.2020.01.13.09.31.26 to 3.1.2020.05.08.09.26.49.

During the upgrade my changes in `/etc/rpki-rtr-server/application.properties` was overwritten.

The Debian package manager allows you to specify config files, so that the package upgrade process allows you to choose an action, e.g. "keep local changes", "install package maintainer version" etc.

I have checked the content of the control folder in the package, and the `conffiles` files content is:
```
/etc/rpki-rtr-server//application-defaults.properties
```

I am not sure exactly how the relation between the `application-defaults.properties` and the `application.properties` files are, perhaps it should be `application.properties` that should be the config file and not the other way round?

**Comment by ties** [comment]
Thanks for the report. You caught two relevant things. The relation between `application.properties` and `application-default.properties` is not clear.

I changed the packaging to mark `/etc/rpki-rtr-server/application.properties` as a config file (on my local branch). This will be included in the next release.

**Comment by kpostrup** [comment]
@ties just wanted to let you know that I have just upgraded to the new rpki-rtr-server-3.1-2020.05.22.11.25 and it is now working perfectly. Closing this issue. Thank you.

**Comment by ties** [comment]
Thanks for the update!
