### ISSUE TITLE
Does this repo support aspa pair?

### ISSUE THREAD

**Issue by loganjingdi** [RIPE-NCC/rpki-validator-3#206]
HI, I have read about this:
RPKI Validator Set up to run as a daemon, and has the following features:
- Supports all current RPKI objects: certificates, manifests, CRLs, ROAs, router certificates, and ghostbuster records。
I really wonder whether this repo support aspa-verification(draft-ietf-sidrops-aspa-verification-01)? 
If not, is there any plan to support it in the future ?
Thank a lot !

**Comment by wibisono** [comment]
Hi, we have not yet support ASPA in this implementation. Maybe not in the near future, if you follow discussion on IETF/SIDROPS, there are some potential relaying party behaviour changes that is being discussed and which likely to have higher priority to be implemented before we look into ASPA.

**Comment by lolepezy** [comment]
Just to add what @wibisono already said.

1) At the moment ASPA is an IETF draft, so even though it seems like it's going to be standardised in the future, it's not in its final shape yet. We will schedule ASAP support when the IETF draft is finished.

2) AFAIK there's no organisation (or software, such as Krill) supporting creation of ASPA objects. So even if a validator supported validating them there's nobody to generate them yet.

I hope it answers your question.
