### ISSUE TITLE
Debian Package Wiki typo

### ISSUE THREAD

**Issue by marzdgzmn** [RIPE-NCC/rpki-validator-3#207]
Just a minor typo under the "Debian Package" Wiki.

![2020-05-26-113618_827x384_scrot](https://user-images.githubusercontent.com/26958260/82858033-4eb0f080-9f45-11ea-9204-5dd637001956.png)

Under `RPKI-RTR server:`
I think it should be:
`sudo apt install ./rpki-rtr-server-latest.deb`

**Comment by lolepezy** [comment]
Thanks!
It's good to know somebody actually reads them :)

Fixed.
