### ISSUE TITLE
Validation Issues

### ISSUE THREAD

**Issue by Methionyl** [RIPE-NCC/rpki-validator-3#208]
Hello guys.

I'm successfully deployed the rpki-validator-3 and have some issues and questions.

Because the fact that I'm new to this, I compared my validator to the "offical one":
[https://rpki-validator.ripe.net/trust-anchors](https://rpki-validator.ripe.net/trust-anchors)

Basically the questions (attached with screenshots), why there are lower number of processed items on my side (is it good or bad?) and what are the meaning these validation issues.

My side:
![image](https://user-images.githubusercontent.com/40830475/82874862-e9ee9980-9f36-11ea-95da-20defb6b3727.png)

RIPE NNC side:
![image](https://user-images.githubusercontent.com/40830475/82874890-f3780180-9f36-11ea-9659-4277b0bd6b03.png)

And the validation issues with my side:
![image](https://user-images.githubusercontent.com/40830475/82874967-0ee30c80-9f37-11ea-9999-2b15540f1017.png)
![image](https://user-images.githubusercontent.com/40830475/82874991-16a2b100-9f37-11ea-8114-62eaf3b37475.png)

And some logs if needed:
`May 26 09:36:41 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:36:41,856          WARN           quartzScheduler_Worker-10                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://cc.rg.net/rrdp/notify.xml: Error downloading 'https://cc.rg.net/rrdp/notify.xml', cause: failed reading response stream for https://cc.rg.net/rrdp/notify.xml: java.net.UnknownHostException: cc.rg.net, cause: cc.rg.net
May 26 09:37:03 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:37:03,574          WARN           quartzScheduler_Worker-6                          n.r.r.v.d.v.CertificateTreeValidationService                  SLOW: Tree validation succeeded for ARIN in 200100ms
May 26 09:38:41 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:38:41,915          WARN           quartzScheduler_Worker-8                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://cc.rg.net/rrdp/notify.xml: Error downloading 'https://cc.rg.net/rrdp/notify.xml', cause: failed reading response stream for https://cc.rg.net/rrdp/notify.xml: java.net.UnknownHostException: cc.rg.net, cause: cc.rg.net
May 26 09:39:51 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:39:51,867          WARN           quartzScheduler_Worker-4                          n.r.r.v.d.v.CertificateTreeValidationService                  SLOW: Tree validation succeeded for APNIC RPKI Root in 220272ms
May 26 09:40:00 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:40:00,254          WARN           quartzScheduler_Worker-2                          n.r.r.v.d.v.CertificateTreeValidationService                  SLOW: Tree validation succeeded for RIPE NCC RPKI Root in 376800ms
May 26 09:40:41 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:40:41,836          WARN           quartzScheduler_Worker-9                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://cc.rg.net/rrdp/notify.xml: Error downloading 'https://cc.rg.net/rrdp/notify.xml', cause: failed reading response stream for https://cc.rg.net/rrdp/notify.xml: java.net.UnknownHostException: cc.rg.net, cause: cc.rg.net
May 26 09:42:42 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:42:42,031          WARN           quartzScheduler_Worker-5                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://cc.rg.net/rrdp/notify.xml: Error downloading 'https://cc.rg.net/rrdp/notify.xml', cause: failed reading response stream for https://cc.rg.net/rrdp/notify.xml: java.net.UnknownHostException: cc.rg.net, cause: cc.rg.net
May 26 09:43:16 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:43:16,145          WARN           quartzScheduler_Worker-10                          n.r.r.v.d.v.CertificateTreeValidationService                  SLOW: Tree validation succeeded for APNIC RPKI Root in 204253ms
May 26 09:44:41 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:44:41,953          WARN           quartzScheduler_Worker-5                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://cc.rg.net/rrdp/notify.xml: Error downloading 'https://cc.rg.net/rrdp/notify.xml', cause: failed reading response stream for https://cc.rg.net/rrdp/notify.xml: java.net.UnknownHostException: cc.rg.net, cause: cc.rg.net
May 26 09:46:41 rpki-validator rpki-validator-3.sh[9397]: 2020-05-26 09:46:41,873          WARN           quartzScheduler_Worker-3                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://cc.rg.net/rrdp/notify.xml: Error downloading 'https://cc.rg.net/rrdp/notify.xml', cause: failed reading response stream for https://cc.rg.net/rrdp/notify.xml: java.net.UnknownHostException: cc.rg.net, cause: cc.rg.net
`
validator.version=3.1-2020.05.08.09.26.49

Thank you for your support

**Comment by lolepezy** [comment]
Hi,

That sounds about normal, the repository "rpki.cnnic.cn" is quite often unavailable,  "cc.rg.net" is sometimes available and "rpkica.mkcay.com" I have never seen responding.

The main difference between your fresh instance and ours is that _sometimes_ the validator can reach them, so the objects get cached and until they are not expired, they are used. So if you keep it running for long enough (hours? days?) it should manage to fetch the objects from the flaky repositories and cache them. There's an ongoing discussion in SIDROPS if the behaviour must be more strict, but for the moment that's how it works.

**Comment by Methionyl** [comment]
Hi,

Thank you for your reply.

The validator itself:
   Active: active (running) since Fri 2020-05-22 11:37:07 CEST; 5 days ago

Then, I'm trying to test in a productive network and we will see how it is going. Of course with proper routing-policies (not rejecting invalid route yet)

Also 1 more question (ignore it if it's beyond the discuss topic)
This is what I see in my Juniper router but those numbers, I can't decide whether is plenty or missing more:

root@R1> show validation statistics
Total RV records: 150419
Total Replication RV records: 150419
  Prefix entries: 138668
  Origin-AS entries: 150419
Memory utilization: 45401468 bytes
Policy origin-validation requests: 0
  Valid: 0
  Invalid: 0
  Unknown: 0
BGP import policy reevaluation notifications: 267007
  inet.0, 236250
  inet6.0, 30757

Note: No Policy origin-validation at this time

**Comment by wibisono** [comment]
Maybe this sample output from juniper website helps. 
https://www.juniper.net/documentation/en_US/junos/topics/topic-map/bgp-origin-as-validation.html#id-displaying-validation-information

```
Total RV records: 3
Total Replication RV records: 3
  Prefix entries: 3
  Origin-AS entries: 3
Memory utilization: 9789 bytes
Policy origin-validation requests: 114
  Valid: 32
  Invalid: 54
  Unknown: 28
BGP import policy reevaluation notifications: 156
  inet.0, 156
  inet6.0, 0
```
Setting up the router itself is out of  my  domain knowledge, yet I wonder why policy origin validation request is 0 on your case, maybe some configuration steps is needed

**Comment by djimie** [comment]
Hello,
i have the same issue with validation to https://rpki-ca.idnic.net/rrdp/notification.xml

May 27 19:17:02 rpki-validator rpki-validator-3.sh[32212]: 2020-05-27 19:17:02,153          WARN           quartzScheduler_Worker-6                          n.r.r.v.r.RrdpServiceImpl                  Error retrieving RRDP repository at https://rpki-ca.idnic.net/rrdp/notification.xml: Error downloading 'https://rpki-ca.idnic.net/rrdp/notification.xml', cause: failed reading response stream for https://rpki-ca.idnic.net/rrdp/notification.xml: java.net.UnknownHostException: rpki-ca.idnic.net, cause: rpki-ca.idnic.net

Had tried to download manually with wget and it worked.

I have checked all issues opened that related to my case, but cant find solution until now.

thanks for any helps.

**Comment by lolepezy** [comment]
> Hello,
> i have the same issue with validation to https://rpki-ca.idnic.net/rrdp/notification.xml

Hello,

Yes, we noticed that it's down/unavailable from time to time. We don't have control over this repository, so we can't advice you on that unfortunately. By the validator should recover as soon as the repository becomes available again. For example, our instance of the validator successfully fetched the repository not too long ago: https://rpki-validator.ripe.net/trust-anchors/monitor/2 (you can search by "rpki-ca.idnic.net" in the search box of the "repositories" section).

**Comment by lolepezy** [comment]
> Total RV records: 150419
> Total Replication RV records: 150419

That sounds about right -- our instance of the validator says "Showing 1 to 10 of 153138 entries" for VRPs (https://rpki-validator.ripe.net/roas), but it works for much longer and has fetched more repositories, including the ones that are often unavailable.

**Comment by AlexanderBand** [comment]
> Yes, we noticed that it's down/unavailable from time to time.

In my experience the IDNIC repo can be slow but it's never completely down:

<img width="1599" alt="Screenshot 2020-06-03 at 15 45 02" src="https://user-images.githubusercontent.com/3448859/83644201-514cbf00-a5b1-11ea-8aa7-ee1b38c29e70.png">

Seen from Western European topology, most Asian repositories (IDNIC, CNNIC, TWNIC, JPNIC and also APNIC) can be quite slow from time to time. We tested from a VM in Singapore and delays were much less severe. IPv4 and/or IPv6 connectivity could also impact the performance quite significantly. 

Some of these organisations could perhaps consider using a CDN for their RRDP endpoint.

**Comment by wibisono** [comment]
At the time when @djimie commented there were two rrdp repo visible from idnic, one with https://rpki-ca.idnic.net and another one https://rpki.idnic.net. The latter seems to be a misconfiguration, and it had been fixed now. The fixed version seems to be OK.
