### ISSUE TITLE
Our result is different from https://rpki-validator.ripe.net

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#210]
our validator:

![Screenshot 2020-06-02 at 4 09 50 PM](https://user-images.githubusercontent.com/59159878/83496403-a1f9e480-a4eb-11ea-82c6-7471010c4f7b.png)

 https://rpki-validator.ripe.net
![Screenshot 2020-06-02 at 4 10 00 PM](https://user-images.githubusercontent.com/59159878/83496454-b342f100-a4eb-11ea-8a65-652c1d06e13f.png)

and we found that there are localhost errors under LACNIC RPKI Root, Could we know there is some wrong?
![Screenshot 2020-06-02 at 4 12 25 PM](https://user-images.githubusercontent.com/59159878/83496562-dd94ae80-a4eb-11ea-8f84-c8cb4f0c37fb.png)

**Comment by ties** [comment]
Hi,

There were repositories with illegal URLs under the LACNIC trust anchor. I do not see them in validator instance for which I recently reset the database.

Can you try pressing the delete button next to these repositories and see if they reappear?

**Comment by JC-ZI** [comment]
Hi, 

Can you try pressing the delete button next to these repositories and see if they reappear? 
[JC]: Thanks. I just deleted these repositories. Thanks. may update the result after one day. Thanks.
