### ISSUE TITLE
RRDP port - Firewall need to open?

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#221]
Now, we permit 80, 443, rsync ports on our firewall,
but we observed there is RRDP port is being used. Would you please recommend is it official port need to be permit? if so, please also advise the dst ip. Thanks.

 
![Screenshot 2020-06-16 at 10 09 00 AM](https://user-images.githubusercontent.com/59159878/84723923-6a923a00-afb9-11ea-91ee-b70dc0e4221d.png)

**Comment by ties** [comment]
Hi,

RRDP is using the https port. In the screenshot that you show, the bottom repository was recently validated but seems to be no longer available (404 when testing).

The top URL should be available. Can you try loading it with curl?

I see the following output:
```
$ curl https://rpki-ca.idnic.net/rrdp/notification.xml -v 2>&1 | head -n 40
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to rpki-ca.idnic.net port 443 (#0)
*   Trying 203.119.13.219...
* Connected to rpki-ca.idnic.net (203.119.13.219) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=rpki-ca.idnic.net
*       start date: May 07 14:00:43 2020 GMT
*       expire date: Aug 05 14:00:43 2020 GMT
*       common name: rpki-ca.idnic.net
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /rrdp/notification.xml HTTP/1.1
> User-Agent: curl/7.29.0
> Host: rpki-ca.idnic.net
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Tue, 16 Jun 2020 12:27:06 GMT
< Content-Length: 202366
< Connection: keep-alive
<
{ [data not shown]
<notification xmlns="http://www.ripe.net/rpki/rrdp" version="1" session_id="8b249df9-4a4a-4545-9296-6f7f64847c6c" serial="11773">
  <snapshot uri="https://rpki-ca.idnic.net/rrdp/8b249df9-4a4a-4545-9296-6f7f64847c6c/11773/snapshot.xml" hash="93e7f3ecdc44043c9c0f3235704de306f28508b813f81d64b863546be3e6f1da" />
...
```

**Comment by JC-ZI** [comment]
Thanks a lot.
curl https://rpki-ca.idnic.net/rrdp/notification.xml -v 2>&1 | head -n 40 <-- this command is for reloading?

Seems is ok now.

**Comment by ties** [comment]
> curl https://rpki-ca.idnic.net/rrdp/notification.xml -v 2>&1 | head -n 40 <-- this command is for reloading?

That command was to check whether you could retrieve it locally.
 
> Seems is ok now.

It probably was a temporary failure. Glad to hear that it has solved itself.
