### ISSUE TITLE
traceback on connection timeout

### ISSUE THREAD

**Issue by dwcarder** [RIPE-NCC/rpki-validator-3#24]
I think this is largely cosmetic, but this exception could be caught so as not to be so verbose.

Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: 2018-04-03 15:54:15.726 ERROR 11496 --- [eduler_Worker-4] net.ripe.rpki.validator3.util.Http       : Error
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect Timeout
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:221) ~[jetty-client-9.4.8.v20171121.jar!/:9.4.8.v20171121]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.util.Http.readStream(Http.java:68) ~[classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.rrdp.HttpRrdpClient.readStream(HttpRrdpClient.java:67) [classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.rrdp.RrdpService.doStoreRepository(RrdpService.java:88) [classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.rrdp.RrdpService.storeRepository(RrdpService.java:77) [classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.rrdp.RrdpService$$FastClassBySpringCGLIB$$827bda13.invoke(<generated>) [classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) [spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.rrdp.RrdpService$$EnhancerBySpringCGLIB$$601d0cd8.storeRepository(<generated>) ~[classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.domain.validation.RpkiRepositoryValidationService.validateRpkiRepository(RpkiRepositoryValidationService.java:123) ~[classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.domain.validation.RpkiRepositoryValidationService$$FastClassBySpringCGLIB$$902e3b5f.invoke(<generated>) ~[classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) [spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.domain.validation.RpkiRepositoryValidationService$$EnhancerBySpringCGLIB$$6965603c.validateRpkiRepository(<generated>) ~[classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at net.ripe.rpki.validator3.adapter.jpa.QuartzRpkiRepositoryValidationJob.execute(QuartzRpkiRepositoryValidationJob.java:60) ~[classes!/:3.0-SNAPSHOT]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.0.jar!/:na]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.0.jar!/:na]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: Caused by: java.net.SocketTimeoutException: Connect Timeout
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at org.eclipse.jetty.io.ManagedSelector$ConnectTimeout.run(ManagedSelector.java:728) ~[jetty-io-9.4.8.v20171121.jar!/:9.4.8.v20171121]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Apr 03 15:54:15 vm1 rpki-validator-3.sh[11496]: 2018-04-03 15:54:15.726  WARN 11496 --- [eduler_Worker-4] n.ripe.rpki.validator3.rrdp.RrdpService  : Error retrieving RRDP repository at https://rpki.cnnic.cn/rrdp/notify.xml: Error downloading 'https://rpki.cnnic.cn/rrdp/notify.xml'

**Comment by timbru** [comment]
Hi,

I agree, and I thought I put this on the list for the team already, but it seems it didn't make it to master yet. I will check..

**Comment by timbru** [comment]
This is solved in the latest builds. I spotted one other stack trace for a harmless issue (the schedular), but that still needs to be resolved.
