### ISSUE TITLE
Docker images not up-to-date

### ISSUE THREAD

**Issue by afenioux** [RIPE-NCC/rpki-validator-3#256]
Hello,

I found 2 repo for the docker image :
https://hub.docker.com/r/ripencc/rpki-validator-3 and https://hub.docker.com/r/ripencc/rpki-validator-3-docker
Actually when running :latest from both repo, In noticed they are not the same release and not 3.1 (but Version: 3.0-SNAPSHOT)

**Comment by fendemann** [comment]
Hi,
try ripencc/rpki-validator-3:latest which created an installation saying it is Version: 3.0-SNAPSHOT, but it provides /metrics information, so It must be version 3.1. The documentation under [https://hub.docker.com/r/ripencc/rpki-validator-3-docker](https://hub.docker.com/r/ripencc/rpki-validator-3-docker) is not correct regarding the docker pull commands.

**Comment by ties** [comment]
Hi,

Thanks for noticing this issue. `ripencc/rpki-validator-3` was the up to date repo. I have manually pushed the current image to the legacy repository as well and CI should pick this up in the future. This buys us time to figure out how to decommission that repository.

Where do you see that you are running `3.0-SNAPSHOT`?
I just tried running it and in `http://localhost:8080/api/healthcheck` I see `buildInformation.version: "3.1-2020.08.20.14.52"`.

We should make sure the version you see reflects reality :).

**Comment by ties** [comment]
I'm closing this issue since I think it is resolved. If you have any further questions, please do not hesitate to contact us or re-open it!
