### ISSUE TITLE
rpki-validator-3.service ***failed regularly***

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#266]
The service terminates regular. Please advise the solution. Thanks.

**Sep 01 10:58:12**
Error retrieving RRDP repository at https://krill.heficed.net/rrdp/notification.xml: Error downloading 'https://krill.heficed.net/rrdp/notification.xml', cause: unexpected response status 403 for https://krill.heficed.net/rrdp/notification.xml
systemd[1]: **rpki-validator-3.service: main process exited, code=exited, status=3/NOTIMPLEMENTED**
systemd[1]: Unit rpki-validator-3.service entered failed state.
systemd[1]: rpki-validator-3.service failed.
systemd[1]: rpki-validator-3.service holdoff time over, scheduling restart.
systemd[1]: Stopped RPKI Validator.
systemd[1]: Started RPKI Validator.

**Sep 01 11:06:36**
Error retrieving RRDP repository at https://krill.mznet.com.br/rrdp/notification.xml
rpki-validator-3.sh[15717]: **Terminating due to java.lang.OutOfMemoryError: GC overhead limit exceeded**
systemd[1]: rpki-validator-3.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
systemd[1]: Unit rpki-validator-3.service entered failed state.
systemd[1]: rpki-validator-3.service failed.
systemd[1]: rpki-validator-3.service holdoff time over, scheduling restart.
systemd[1]: Stopped RPKI Validator.
systemd[1]: Started RPKI Validator.

![error image](https://user-images.githubusercontent.com/59159878/91792521-40f7bf00-ec48-11ea-8c45-d03f0fc6fe59.png)

**Comment by JC-ZI** [comment]
dear support,
any update?

**Comment by ties** [comment]
Let's solve & track this in issue #267.
