### ISSUE TITLE
Which is the stable version of the Validator 3 Production

### ISSUE THREAD

**Issue by JC-ZI** [RIPE-NCC/rpki-validator-3#271]
Hi support,

We updated one of our validator to 3.1-2020.08.31.13.36.06 last 2 weeks.

We have do the same task on another one this morning:
(Q1) the version we get from the website link it is older than 3.1-2020.08.31.13.36.06. is it correct?
rpki-rtr-server-3.1-2020.08.20.14.52.noarch.rpm
rpki-validator-3.1-2020.08.20.14.52.noarch.rpm

(Q2) We followed up the steps of the link below, Our OS is CentOS7.
https://github.com/RIPE-NCC/rpki-validator-3/wiki/RIPE-NCC-RPKI-Validator-3-Production#CentOS-7
the version number of application-default.properties has NOT been changed to 2020.08.20.14.52. Is it a problem?

(Q3) Where can i know we are running which version or which versions we have downloaded?

Thanks.

**Comment by JC-ZI** [comment]
Dear Support,
May we have update?
Thanks.

**Comment by ties** [comment]
Hi,

My apologies for the late reply. The latest release is `3.1-2020.09.25.11.16` and we recommend an upgrade to that version. When upgrading, the `validator.version` key in `application-defaults.properties` should be overwritten. User modifications should be in `application.properties`.

The latest release now the version in the footer `Copyright ©2009-2020 the Réseaux IP Européens Network Coordination Centre RIPE NCC. All rights restricted. Version: 3.1-2020.09.25.11.16`. I hope this clarifies things!
