### ISSUE TITLE
high I/O

### ISSUE THREAD

**Issue by dia-de-muertos** [RIPE-NCC/rpki-validator-3#296]
Hello,
is it 'normal' that the validator has heavy disk access, especially read?

```
# iostat -dmx sda1 1 5
Linux 3.10.0-1160.2.2.el7.x86_64 (rpki.inet.dienste) 	11/18/2020 	_x86_64_	(3 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.02    89.60  900.28   96.45    13.19     1.28    29.74     2.40    2.41    1.76    8.49   0.23  22.66

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00 4204.00    0.00    82.82     0.00    40.35     8.03    1.91    1.91    0.00   0.14  59.30

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00 3371.00    0.00    65.38     0.00    39.72     4.14    1.23    1.23    0.00   0.14  48.70

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00 1597.00    0.00    67.39     0.00    86.43     2.38    1.49    1.49    0.00   0.27  42.40

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00 1305.00    0.00    93.50     0.00   146.74     1.65    1.26    1.26    0.00   0.21  27.40
```

This is with rpki.validator.rpki.object.cleanup.grace.duration=P3D
Going with 7 days, our machine has nearly 100% io-wait.

Regards
 Stefan

**Comment by ties** [comment]
Hi,

On one of our instances, the IO load is much lower:
```
$  iostat -dmx sda1 1 5
Linux 3.10.0-957.21.3.el7.x86_64 (host) 	11/18/2020 	_x86_64_	(4 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00    0.00    0.04     0.00     0.00     7.45     0.00    1.28    1.84    1.28   1.28   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

How much memory does the machine have? The reads should almost completely come from the (linux) buffer cache if there is sufficient memory available.

Kind regards,
Ties

**Comment by dia-de-muertos** [comment]
Hi,
that's strange. The VM currently has 6G RAM:
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           5.7G        3.6G        129M         24M        1.9G        1.8G
Swap:            0B          0B          0B
```
As we only keep 3 days data, the size is slightly smaller:
```
# du -h -s /var/lib/rpki-validator-3/
3.3G	/var/lib/rpki-validator-3/
```
Can I debug what is producing so many r/w access?
Validator version is 2020.10.28

Regards
 Stefan

**Comment by ties** [comment]
Hi,

Unfortunately it is really hard to debug what is causing the reads. The database library (xodus) uses memory mapped IO.

There are two scenarios that I'm thinking off:
   * The database could be degraded.
    * You can try to remove `/var/lib/rpki-validator-3/db` at let it re-initialise itself. Please make sure that any additional TALs (i.e. ARIN) are in `/var/lib/rpki-validator-3/preconfigured-tals` so they are picked up automatically.
  * The root cause is memory pressure - the machines that are running fine have 8GB of ram

Can you try one of these approaches?

**Comment by dia-de-muertos** [comment]
Hello,
did all. Removed `/var/lib/rpki-validator-3/preconfigured-tals`, all TALs are in `/var/lib/rpki-validator-3/preconfigured-tals` and increased RAM to 8GB.
As the I/O increases with time (filling up the db directory), we have to wait a couple of days to see if there's any difference.

Thanks for your help
 Stefan

**Comment by dia-de-muertos** [comment]
Hi,
upgrading to 8GB RAM seemed to be successfull.
The server is running with 'normal' I/O since then.
Thanks for the fast help.

Stefan

**Comment by ties** [comment]
Hi Stefan,

Good to hear that. It is a bit unfortunate that the working set has crept up to this size, but now at least we know where the point for the memory/io tradeoff is.

Ties
