### ISSUE TITLE
Validator keeps hammering old SIAs?

### ISSUE THREAD

**Issue by job** [RIPE-NCC/rpki-validator-3#307]
I operated a CA with the publication point's notification URL at `https://chloe.sobornost.net/rpki/notify.xml`, but  since then this CA has been revoked. However I see instances of the ripe validator continuing to request the `/rpki/notify.xml` file (which no longer exists) every minute.

This is yesterday's log

```
$ cat chloe.access.log | fgrep ' 404 ' | fgrep 16/Dec/2020 | awk -F'" "' '{ print $NF }' | sort | uniq -c | sort -r -n
46538 RIPE NCC RPKI Validator/3.2-2020.10.28.23.06"
24644 RIPE NCC RPKI Validator/3.1-2020.09.25.11.16"
12690 RIPE NCC RPKI Validator/3.1-2020.05.22.11.25"
11213 RIPE NCC RPKI Validator/3.1-2020.07.06.14.28"
10667 RIPE NCC RPKI Validator/3.1-2020.01.13.09.31.26"
9007 RIPE NCC RPKI Validator/3.1-2020.08.20.14.52"
8051 RIPE NCC RPKI Validator/3.2-2020.12.10.13.57"
5229 RIPE NCC RPKI Validator/3.1-2020.08.06.14.39"
4051 RIPE NCC RPKI Validator/3.1-2020.05.08.09.26.49"
2524 Jetty/9.4.12.v20180830"
2164 Cloudflare-RPKI-RRDP/1.0 (+https://rpki.cloudflare.com)"
1440 RIPE NCC RPKI Validator/3.2-2020.12.09.16.07.04"
1296 RIPE NCC RPKI Validator/"
1207 RIPE NCC RPKI Validator/3.1-2019.11.08.15.24.50"
 985 Jetty/9.4.15.v20190215"
 851 RIPE NCC RPKI Validator/3.1-2019.12.16.15.18.18"
 808 RIPE NCC RPKI Validator/3.1-2020.03.16.13.34.48"
 720 RIPE NCC RPKI Validator/@build.version@-@build.release@"
 720 RIPE NCC RPKI Validator/3.1-2020.09.28.12.55.26"
 720 RIPE NCC RPKI Validator/3.1-2019.10.29_16.55.05"
 720 RIPE NCC RPKI Validator/3.1-2019.08.19_09.00.01"
 525 RIPE NCC RPKI Validator/3.1-2020.03.16.10.26.36"
 510 Cloudflare-RRDP-OctoRPKI v1.2.1 (2020-11-24T03:46:28+0000-travis) (+https://github.com/cloudflare/cfrpki)"
 289 RIPE NCC RPKI Validator/3.2-2020.11.26.16.25.37"
 193 Cloudflare-RRDP-OctoRPKI v1.2.0-6-g55e0d1f (2020-11-24T22:47:10+0000) (+https://github.com/cloudflare/cfrpki)"
 127 Cloudflare-RRDP-OctoRPKI   (+https://github.com/cloudflare/cfrpki)"
  79 RIPE NCC RPKI Validator/3.0-407"
  65 Cloudflare-RRDP-OctoRPKI v1.2.2 (2020-12-09T09:16:58-0800) (+https://github.com/cloudflare/cfrpki)"
  15 RIPE NCC RPKI Validator/3.1-2020.01.07.14.37.29"
   5 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
   3 Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
   3 (compatible;PetalBot;+https://aspiegel.com/petalbot)"
   2 Mozilla/5.0 zgrab/0.x"
   1 python-requests/2.25.0"
   1 curl/7.29.0"
   1 Routinator/0.8.2"
```

Is there still some SIA somewhere pointing to this notification file?

**Comment by ties** [comment]
Hi,

For versions including https://github.com/RIPE-NCC/rpki-validator-3/pull/263 the repository should be removed after seven days. When was the CA revoked, and do you still observe these requests?

**Comment by job** [comment]
Was revoked ~ a week ago. Requests have now stopped (thankfully).

As RIPE NCC's implementation appears the only one to keep hammering publication points even though the CA referencing it has been revoked, I question if this is desirable behavior. I also suspect this behavior can be misused in a subtle request amplification attack scenario.

You might want to consider to immediately cease querying publication point notification files which are not referenced on any valid current certificate, instead of waiting 7 days. During those 7 days there is nothing for the RP to fetch other than garbage.

**Comment by ties** [comment]
I recognise that this can be misused in a request amplification attack. However I do see this as an accepted risk in the design of RRDP, in my eyes this scenario (varying SIA over time, temporal) is a less effective version of the scenario where you set up parallel SIA's for child-certificates. Please let me know how you view this.

What do you think of:
  * Expiring unused repositories easier, and
  * Investigating a change of the RRDP update interval - for big trust anchors I see around two requests to notification.xml per delta, but on a delegated repository this will be much more skewed.

**Comment by job** [comment]
@ties I'm sorry, I don't understand what you are saying.

Why is the RIPE validator contacting publication points when there is no SIA on any valid certificate pointing to such URLs? Why does it keep contacting URLs for multiple days? The validator won't be able to use any data retrieved from the URL, any RRDP updates fetched (or who knows what the validator is fetching) would be trash data from a validation perspective.

Other validator's don't contact the SIA URL after certificate revocation/expiry/invalidation. RIPE NCC's validator seems unique in this regard. Would it not make sense to align the behavior of this software with what other validators do?

**Comment by ties** [comment]
Why? Because of implementation choices that were made.

As I mentioned in my previous comment I proposed to expire unreachable repositories earlier and I expect that this will address your concern (i.e. validator instances stop contacting un-referenced repositories earlier). As always, unreachable objects are not included in validation.

**Comment by ties** [comment]
The change to a lower timeout before an unreachable repository is removed, and lower number of RRDP has been merged and is included in the new release candidate (`rpki-validator-3.2-2020.12.21.14.45.40`).

Please test this release if applicable, and let us know if you have any further feedback.
