### ISSUE TITLE
GET a ROA directly

### ISSUE THREAD

**Issue by job** [RIPE-NCC/rpki-validator-3#38]
With RPKI Validator v2 it was possible to query directly to a ROA: 

http://localcert.ripe.net:8088/roas?q=2001:67c:208c::/48

But with the new RPKI Validator this no longer seems possible:

https://rpki.meerval.net/roas?q=2001:67c:208c::/48

This was a very useful feature to me to link directly to the source of routing information

**Comment by dacruz** [comment]
Yes, I can see how that would be useful. 
We’ll keep it in mind for future releases. 

Cheers, 
Thiago da Cruz

**Comment by dwcarder** [comment]
@job I know of one way to get close via the api, ex:
`curl -H "Accept: application/json" 'https://rpki.meerval.net/api/bgp/validity/?prefix=1.0.0.0/24&asn=13335'`

**Comment by job** [comment]
Not good enough. Need something that works in browsers that humans use.
Like with the previous validator.

**Comment by dwcarder** [comment]
Ah, those pesky humans.  Yes, I would certainly like that feature parity as well.

**Comment by timbru** [comment]
This will work:
https://rpki.meerval.net/announcement-preview?asn=AS15562&prefix=2001:67c:208c::%2F48

But is not quite the same as having a bookmarkable query parameter for the search on the ROA and/or BGP Preview pages

**Comment by job** [comment]
thanks @timbru - this is very helpful!

(I'd still love `?q=xxx` approach)

**Comment by job** [comment]
Can this be put on a backlog? I really need the ability to HTTP GET directly towards a ROA

**Comment by dacruz** [comment]
Hi Job, 

It’s already on our internal backlog.

**Comment by lolepezy** [comment]
The latest build includes this functionality
https://rpki-validator.ripe.net/roas?q=2001:67c:208c::/48
Have fun!
