### ISSUE TITLE
Provide Debian package

### ISSUE THREAD

**Issue by job** [RIPE-NCC/rpki-validator-3#40]
In addition to the CentOS package I think it would be good if Debian packages are also provided. To reduce workload, only Debian 9 needs to be supported at this moment.

**Comment by dacruz** [comment]
Added to the backlog.

**Comment by lolepezy** [comment]
Please try the Debian package here
https://ftp.ripe.net/tools/rpki/validator3/prod/deb/

Note that at the moment it is not a repository, so you will have to use something like 
apt install ./rpki-validator-XXX.deb, but we will start hosting the repository as the next step.
