### ISSUE TITLE
expose RIS dump timestamp via API and BGP Preview UI

### ISSUE THREAD

**Issue by nusenu** [RIPE-NCC/rpki-validator-3#49]
It would be really valuable to know, what data we see when looking at the BGP Preview data and UI page.
More specifically:
* From what time is the RIS dump that is being used?

Note: This information has been available in RPKI Validator 2.x as can bee seen here:
http://localcert.ripe.net:8088/bgp-preview ("The RIPE NCC Route Collector information that was last updated X hours and XX minutes ago.")

I'd propose to expose the timestamp of the RIS dumps on ris.ripe.net/dumps (NOT the timestamp when it was fetched from there).

ref: https://twitter.com/alexander_band/status/1043846204608704512

**Comment by dacruz** [comment]
Feature request added to the backlog.

**Comment by lolepezy** [comment]
Done in the latest build.

You can see it on the 
https://rpki-validator.ripe.net/bgp-preview page
and also it is reflected in the 
https://rpki-validator.ripe.net/api/healthcheck/

**Comment by nusenu** [comment]
> and also it is reflected in the
> https://rpki-validator.ripe.net/api/healthcheck/

should there be a timestamp in the healthcheck response?
```
{
  "data" : {
    "trustAnchorReady" : {
      "AfriNIC RPKI Root" : true,
      "LACNIC RPKI Root" : true,
      "APNIC RPKI Root" : true,
      "RIPE NCC RPKI Root" : true,
      "ARIN" : true
    },
    "bgpDumpReady" : {
      "http://www.ris.ripe.net/dumps/riswhoisdump.IPv6.gz" : true,
      "http://www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz" : true
    },
    "databaseStatus" : "OK"
  }
}
```
