### ISSUE TITLE
RPKI validator 3 fetches RIS dumps over an insecure connection (plain HTTP)

### ISSUE THREAD

**Issue by nusenu** [RIPE-NCC/rpki-validator-3#50]
RPKI validator 3 fetches RIS dumps from:
http://www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz
Is that gz file authenticated via some out of band mechanism  or is RPKI validator trusting RIS dumps fetched via an insecure connection for its BGP preview functionality?

that resource is apparently not available via HTTPS yet:
https://www.ris.ripe.net/dumps/riswhoisdump.IPv4.gz (timeout)

This issue is about changing this to 
* offer RIS dumps via HTTPS
* configure RPKI validator 3 to fetch it via HTTPS

**Comment by dacruz** [comment]
The people responsible for the RIS dump was already informed. We'll change it  the config when the HTTPS is available.

**Comment by nusenu** [comment]
fixed in 387 according to 
https://www.ripe.net/ripe/mail/archives/routing-wg/2019-March/003736.html
