### ISSUE TITLE
SQL errors from RPKI validator

### ISSUE THREAD

**Issue by devicenull** [RIPE-NCC/rpki-validator-3#51]
<pre>
Nov  8 14:36:50 rpki1 rpki-validator-3.sh[14332]: 2018-11-08 14:36:50,184 #011 WARN  #011 quartzScheduler_Worker-5 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Nov  8 14:36:50 rpki1 rpki-validator-3.sh[14332]: 2018-11-08 14:36:50,184 #011 ERROR #011 quartzScheduler_Worker-5 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'8bacd717592e44482105a03be331a6a73db7354cf8070e707dfc8395151cc87a', 18821461)"; SQL statement:
Nov  8 14:36:50 rpki1 rpki-validator-3.sh[14332]: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Nov  8 14:36:50 rpki1 rpki-validator-3.sh[14332]: 2018-11-08 14:36:50,184 #011 ERROR #011 quartzScheduler_Worker-5 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
Nov  8 14:37:51 rpki1 rpki-validator-3.sh[14332]: 2018-11-08 14:37:51,154 #011 WARN  #011 quartzScheduler_Worker-4 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Nov  8 14:37:51 rpki1 rpki-validator-3.sh[14332]: 2018-11-08 14:37:51,154 #011 ERROR #011 quartzScheduler_Worker-4 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'8bacd717592e44482105a03be331a6a73db7354cf8070e707dfc8395151cc87a', 18821461)"; SQL statement:
Nov  8 14:37:51 rpki1 rpki-validator-3.sh[14332]: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Nov  8 14:37:51 rpki1 rpki-validator-3.sh[14332]: 2018-11-08 14:37:51,154 #011 ERROR #011 quartzScheduler_Worker-4 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
</pre>

**Comment by devicenull** [comment]
This is with 3.0-324

**Comment by devicenull** [comment]
Still happens with 3.0-333.  I'm not doing anything special here, just wipe the database and restart and you'll see it within a couple minutes

<pre>
2019-01-10T18:02:57.188106+00:00 rpki1 rpki-validator-3.sh[17445]: 2019-01-10 18:02:57,177 #011 WARN  #011 quartzScheduler_Worker-2 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
2019-01-10T18:02:57.188405+00:00 rpki1 rpki-validator-3.sh[17445]: 2019-01-10 18:02:57,177 #011 ERROR #011 quartzScheduler_Worker-2 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'ec29197e130f6dc8cf0a8ac7a3224c92af39f27d87a2b07403fb9b2432508e9f', 100022)"; SQL statement:
2019-01-10T18:02:57.188558+00:00 rpki1 rpki-validator-3.sh[17445]: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
2019-01-10T18:02:57.188721+00:00 rpki1 rpki-validator-3.sh[17445]: 2019-01-10 18:02:57,179 #011 ERROR #011 quartzScheduler_Worker-2 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
</pre>

**Comment by lolepezy** [comment]
Hi devicenull,

Even though the message has the error status, there's nothing critical about it -- it just means the validator will not insert an object with the same hash to the local storage twice. But we will fix the error message so that it's not so confusing.

**Comment by jengyic** [comment]
Hi lolepezy,

I got similar error messages from 3.0-335. 
O.S. is CentOS 7.6.1810 (Core) with SELinux enabled. 
JDK is java-1.8.0-openjdk.

Error message:
<pre>
Mar 12 23:24:28 rpkival3 rpki-validator-3.sh: 2019-03-12 23:24:28,981 #011 WARN  #011 pool-1-thread-1 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Mar 12 23:24:28 rpkival3 rpki-validator-3.sh: 2019-03-12 23:24:28,981 #011 ERROR #011 pool-1-thread-1 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SH
A256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'ec774ef5f67ca30de8a89ad33ab8833d6e1260242f6231cca031641f9c109a88', 50708173)"; SQL statement:
Mar 12 23:24:28 rpkival3 rpki-validator-3.sh: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_
at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Mar 12 23:24:28 rpkival3 rpki-validator-3.sh: 2019-03-12 23:24:28,981 #011 ERROR #011 pool-1-thread-1 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hiberna
te.exception.ConstraintViolationException: could not execute statement]
Mar 12 23:25:18 rpkival3 rpki-validator-3.sh: 2019-03-12 23:25:18,748 #011 ERROR #011 pool-1-thread-1 #011#011#011 o.s.s.s.TaskUtils$LoggingErrorHandler #011#011 Unexpected error occurred in scheduled task.
Mar 12 23:25:18 rpkival3 rpki-validator-3.sh: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256
) VALUES (X'ec774ef5f67ca30de8a89ad33ab8833d6e1260242f6231cca031641f9c109a88', 50708173)"; SQL statement:
Mar 12 23:25:18 rpkival3 rpki-validator-3.sh: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_
at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`
</pre>

After restart rpki-validator-3, I will get some validation issues in some trust anchors.
So upgrade to 3.0-387. Following is the upgrade procedures.

<pre>
wget https://ftp.ripe.net/ripe/tools/rpki/validator3/archive/centos7/rpki-rtr-server-3.0-387.noarch.rpm
wget https://ftp.ripe.net/ripe/tools/rpki/validator3/archive/centos7/rpki-validator-3.0-387.noarch.rpm

systemctl stop rpki-rtr-server
systemctl stop rpki-validator-3

mv /var/lib/rpki-validator-3/db /var/lib/rpki-validator-3/db.bak-20190314
mv /var/lib/rpki-validator-3/rsync /var/lib/rpki-validator-3/rsync.bak-20190314
mkdir -p /var/lib/rpki-validator-3/db
mkdir -p /var/lib/rpki-validator-3/rsync
chown -R rpki:rpki /var/lib/rpki-validator-3/db
chown -R rpki:rpki /var/lib/rpki-validator-3/rsync
chcon -R system_u:object_r:var_lib_t:s0 /var/lib/rpki-validator-3/db /var/lib/rpki-validator-3/rsync
ls -laZ /var/lib/rpki-validator-3

rpm -e rpki-validator-3.0-390.noarch rpki-rtr-server-3.0-390.noarch
rpm -qa|grep rpki
rpm -Uvh rpki-rtr-server-3.0-387.noarch.rpm rpki-validator-3.0-387.noarch.rpm

Edit config
/etc/rpki-validator-3/application.properties
/etc/rpki-rtr-server/application.properties

systemctl start rpki-validator-3
Wait 4 TALs
/usr/bin/upload-tal.sh arin-ripevalidator.tal http://localhost:8080/
systemctl restart rpki-validator-3`
</pre>

Now I got a lot of error messages in log.

<pre>
Mar 15 08:50:36 rpkival3 rpki-validator-3.sh: 2019-03-15 08:50:36,159 #011 WARN  #011 quartzScheduler_Worker-3 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Mar 15 08:50:36 rpkival3 rpki-validator-3.sh: 2019-03-15 08:50:36,159 #011 ERROR #011 quartzScheduler_Worker-3 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'367e9319ae9fb017e152a82fe16316f0b5a2108b4d97421d91eeedc30c9d2254', 1811419)"; SQL statement:
Mar 15 08:50:36 rpkival3 rpki-validator-3.sh: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Mar 15 08:50:36 rpkival3 rpki-validator-3.sh: 2019-03-15 08:50:36,159 #011 ERROR #011 quartzScheduler_Worker-3 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
Mar 15 08:50:54 rpkival3 rpki-validator-3.sh: 2019-03-15 08:50:54,620 #011 WARN  #011 quartzScheduler_Worker-7 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Mar 15 08:50:54 rpkival3 rpki-validator-3.sh: 2019-03-15 08:50:54,620 #011 ERROR #011 quartzScheduler_Worker-7 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'367e9319ae9fb017e152a82fe16316f0b5a2108b4d97421d91eeedc30c9d2254', 1811419)"; SQL statement:
Mar 15 08:50:54 rpkival3 rpki-validator-3.sh: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Mar 15 08:50:54 rpkival3 rpki-validator-3.sh: 2019-03-15 08:50:54,620 #011 ERROR #011 quartzScheduler_Worker-7 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
Mar 15 08:51:23 rpkival3 rpki-validator-3.sh: 2019-03-15 08:51:23,500 #011 ERROR #011 quartzScheduler_Worker-4 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [net.ripe.rpki.validator3.domain.RpkiRepository#48844]]
Mar 15 08:51:55 rpkival3 rpki-validator-3.sh: 2019-03-15 08:51:55,473 #011 WARN  #011 quartzScheduler_Worker-7 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Mar 15 08:51:55 rpkival3 rpki-validator-3.sh: 2019-03-15 08:51:55,473 #011 ERROR #011 quartzScheduler_Worker-7 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'367e9319ae9fb017e152a82fe16316f0b5a2108b4d97421d91eeedc30c9d2254', 1811419)"; SQL statement:
Mar 15 08:51:55 rpkival3 rpki-validator-3.sh: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Mar 15 08:51:55 rpkival3 rpki-validator-3.sh: 2019-03-15 08:51:55,473 #011 ERROR #011 quartzScheduler_Worker-7 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
Mar 15 08:52:55 rpkival3 rpki-validator-3.sh: 2019-03-15 08:52:55,232 #011 WARN  #011 quartzScheduler_Worker-5 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 23505, SQLState: 23505
Mar 15 08:52:55 rpkival3 rpki-validator-3.sh: 2019-03-15 08:52:55,232 #011 ERROR #011 quartzScheduler_Worker-5 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 Unique index or primary key violation: "RPKI_OBJECT__SHA256_IDX ON PUBLIC.RPKI_OBJECT(SHA256) VALUES (X'367e9319ae9fb017e152a82fe16316f0b5a2108b4d97421d91eeedc30c9d2254', 1811419)"; SQL statement:
Mar 15 08:52:55 rpkival3 rpki-validator-3.sh: /* insert net.ripe.rpki.validator3.domain.RpkiObject */ insert into rpki_object (created_at, updated_at, version, authority_key_identifier, last_marked_reachable_at, serial_number, sha256, signing_time, type, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-197]
Mar 15 08:52:55 rpkival3 rpki-validator-3.sh: 2019-03-15 08:52:55,232 #011 ERROR #011 quartzScheduler_Worker-5 #011#011#011 o.h.i.ExceptionMapperStandardImpl #011#011 HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
</pre>

How to get ride of error messages? If I want to take a look the DB files, how to do that?

Thanks a lot,

Morris Chen
