### ISSUE TITLE
rpki rtr-server won't update router

### ISSUE THREAD

**Issue by dudster83** [RIPE-NCC/rpki-validator-3#52]
Hi
I'd modified the rtr-server's application.properties to use ip:port and than configured a cisco router to use those.
on the cisco router I see that show ip bgp rpki server does communicate with the server.
on the centos hosting the rtr-server I see communication between the router and the app in the port i'm using (bidirectional commuincation)
but no prefix in the router's bgp is being updated, all seems to be uknown. sh ip bgp rpki table is empty.
the router is peering with a route-server, hence, there's another transit as in the as-path, but from what I understand, the validity of the route is checked with the origin AS.

am I missing something? how can I debug it?

for example:
ripe rpki validator shows AS13335  1.1.1.0/24 is a valid ROA

my router hasn't heard of it yet
rpki.hme#sh ip bgp 1.1.1.0/24
BGP routing table entry for 1.1.1.0/24, version 257
      path 7F28E38D5550 RPKI State not found

router also indicates:
*Nov 17 20:07:11.939: %BGP-4-BGP_RPKI_ERROR_MESSAGE: BGP received an RPKI Error Report PDU from rpki server ip/port No Data Available  hex dump 00 02 00 00 00 00 00 08

and sometimes

*Nov 17 20:08:12.071:  BGP SOVC: Skipping serial query for neighbor ip/port because of in-progress query

David

**Comment by dacruz** [comment]
Did you check the rtr-server logs?
$ journalctl -u  rpki-rtr-server

What do you see?

**Comment by dudster83** [comment]
Hi
I see a lot of java notifications
for example
[rpki-server-logs.txt](https://github.com/RIPE-NCC/rpki-validator-3/files/2599715/rpki-server-logs.txt)

**Comment by dudster83** [comment]
fixed.
installed the java and rpki under a non root user solved it.
