### ISSUE TITLE
Invalid notification link?

### ISSUE THREAD

**Issue by devicenull** [RIPE-NCC/rpki-validator-3#53]
Our validator just started spamming this to the console:

    Nov 28 15:17:53 rpki1 rpki-validator-3.sh[13782]: 2018-11-28 15:17:53,474 #011 WARN  #011 quartzScheduler_Worker-7 #011#011#011 n.r.r.v.r.RrdpService #011#011 Error retrieving RRDP repository at https://rrdp.ripe.net/notification.xml/: Error downloading 'https://rrdp.ripe.net/notification.xml/', cause: unexpected response status 404 for https://rrdp.ripe.net/notification.xml/

**Comment by dacruz** [comment]
An extra / was added by mistake to the notification.xml URL. It was already removed and it has no real impact on the publication or the validation at this moment. 

But the validator remember all the repositories it has found in the past and keep trying to reach it again and again. It's a known issue and a clean up procedure will be available in a future release.

**Comment by dacruz** [comment]
Closing issue
