### ISSUE TITLE
BGP Preview Screen

### ISSUE THREAD

**Issue by dudster83** [RIPE-NCC/rpki-validator-3#56]
Hello
I have some issues with the BGP Preview screen when sometimes it displays as a blank screen. 
is this a known issue?
![example](https://user-images.githubusercontent.com/29201833/49718940-5357eb00-fc64-11e8-9af2-db5819ab124e.png)

**Comment by dacruz** [comment]
Do you have any message on the console? Any logs?
Looks like the backend application is not running.

**Comment by dudster83** [comment]
Hi dacruz,
all screens in the rpki validator ui are operational, besides that,
under  journalctl -f -u rpki-validator-3 i see sometimes error regarding java exception of database might be in use.

the server is behind a firewall, and configure behind NAT and NGINX as well. it's open to speak to TAL's repositories, from where is the bgp preview screen generates its data? do i need to permit access to another sources or it is being generated from a local db?

**Comment by omuravskiy** [comment]
Hi dudster83,

You have to open http port for www.ris.ripe.net (note it has both IPv4 and IPv6 addresses).

Cheers,
Oleg

**Comment by dudster83** [comment]
Hi Oleg,
Thanks for replying.
I'd opened http port from rpki server towards ripe.net, ris.ripe.net and guanaco.ripe.net FQDN's and restart the service, with no help.
I'm running tcpdump on the server to see if it tries to communicate with such host, I don't see any matches for it.

**Comment by lolepezy** [comment]
Hi dudster83,

Do you still the problem? 
Could you try the latest build and tell us if the issue is still there?
(preferably with the full log)

**Comment by dudster83** [comment]
Hi @lolepezy 
I'd updated one of the machines to the new build.
from the first look, it looks like it worked without any problems. i'll keep monitoring this and update the second server soon.
Thanks
