### ISSUE TITLE
Using server.servlet.context-path= to change base location?

### ISSUE THREAD

**Issue by zzaflemi** [RIPE-NCC/rpki-validator-3#57]
I'm sorry if this is not the best way/place to ask a question.  I don't see a link to any mailing lists or forums.  

I've setup the rpki-validator-3 on CentOS 7 /w Apache reverse proxy.  Stable Release, rpki-validator-3.0-324 via yum.  I'd like to not have the application as the root level of the site / something like /validator so I can just reverse proxy /validator to it.  I've tried setting the server.servlet.context-path=/validator in /etc/rpki-validator-3/application.properties and restarting the app along with a few other things in Apache but don't seem to be able to get it.  That value / config seems to be ignored.  In the HEAD section of the HTML it spits out still sets <base href="/">.  Which I think might be part of my problem of getting a "blank" page because it can't load any of the .js files it uses and likely other things.  

Anyone have any suggestions or pointers on information on how to set that or what I might be doing wrong?  

In the end maybe I can just work around it in Apache by just proxying a number of specific URLs, but I don't see a list of all the directories/URLs I'd have to reverse proxy.  Part of what I need is for a few paths to not get sent via the reverse proxy in Apache so I can setup the SAML authentication and discovery service in front of it.  So I can't just proxy all of / to the backend.  

Thanks in advance for any ideas.

**Comment by lolepezy** [comment]
Hi, 

The behaviour with changed " server.servlet.context-path" is indeed wrong, we are investigating how to resolve it.

**Comment by lolepezy** [comment]
Hi, 

we fixed the behaviour in the latest build, so you can change 
server.servlet.context-path to something like '/validator/' (with slashes on both ends) and we expect it to work.
