### ISSUE TITLE
rtr.server.address bind to all interfaces

### ISSUE THREAD

**Issue by cwiech** [RIPE-NCC/rpki-validator-3#64]
It doesn't seem possible to configure the rtr.server.address to bind to all interfaces (like the rtr.server will allow by levaing blank), is this possible? I don't want to hard-code the IP address in the configuration, but it seems you have to specify one or it assumes localhost.

**Comment by lolepezy** [comment]
Hi,

Could you try using rtr.server.address=0.0.0.0?
I believe it should do what you want.

**Comment by zzaflemi** [comment]
Or if you have a dual stacked machine with IPv6, you can try 

rtr.server.address=::

That is what I use on CentOS 7 for it to listen on all v4 and v6 addresses.

**Comment by lolepezy** [comment]
Also, I think specifying "rtr.server.address=localhost" explicitly should result in binding to all resolved addresses.
