### ISSUE TITLE
3.0-393 DB stop updating

### ISSUE THREAD

**Issue by pbonbon** [RIPE-NCC/rpki-validator-3#76]
After upgrade to 3.0-393 I have problem with DB, that will stop updating after few hours:

      Mar 18 03:34:41 rpki2 rpki-validator-3.sh: 2019-03-18 03:34:41,607 #011 WARN  #011 quartzScheduler_Worker-8 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 0, SQLState: null
      Mar 18 03:34:41 rpki2 rpki-validator-3.sh: 2019-03-18 03:34:41,607 #011 ERROR #011 quartzScheduler_Worker-8 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 HikariPool-1 - Connection is not available, request timed out after 30001ms.
      Mar 18 03:35:14 rpki2 rpki-validator-3.sh: 2019-03-18 03:35:14,540 #011 WARN  #011 http-nio-127.0.0.1-8080-exec-7 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 SQL Error: 0, SQLState: null
      Mar 18 03:35:14 rpki2 rpki-validator-3.sh: 2019-03-18 03:35:14,540 #011 ERROR #011 http-nio-127.0.0.1-8080-exec-7 #011#011#011 o.h.e.j.s.SqlExceptionHelper #011#011 HikariPool-1 - Connection is not available, request timed out after 30000ms.
      Mar 18 03:35:14 rpki2 rpki-validator-3.sh: 2019-03-18 03:35:14,575 #011 ERROR #011 http-nio-127.0.0.1-8080-exec-7 #011#011#011 o.a.c.c.C.[.[.[.[dispatcherServlet] #011#011 Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] with root cause

**Comment by lolepezy** [comment]
This is a known problem of an underlying database. To fix it quickly, you can simply restart the validator, it should help. In the long term, we are planning to switch to another storage subsystem.
