### ISSUE TITLE
Leave a copy of at least the last few Prod releases in prod repo

### ISSUE THREAD

**Issue by zzaflemi** [RIPE-NCC/rpki-validator-3#80]
You might have reasons for doing this that I don't understand, but I wanted to ask about not moving the RPMs from the Prod repo to archive every time there is a new release.  (Copying them to archive would still seem reasonable.)  

https://ftp.ripe.net/tools/rpki/validator3/prod/centos7/repo/

With a number of bugs in the last few prod releases, I'm downgrading to 379 for now because it was stable for us.  I think I might have even be able to use yum downgrade if the older RPMs were still in the prod repo.  

Thanks for any insight you can provide.

**Comment by lolepezy** [comment]
Hi, 

There's an archive of builds
https://ftp.ripe.net/tools/rpki/validator3/archive/
so you can find builds for the last few months.
