### ISSUE TITLE
Recurring validation issues

### ISSUE THREAD

**Issue by edugas** [RIPE-NCC/rpki-validator-3#91]
Hello,

I've been getting a recurring validation issue with ca.rg.net since the day I installed the validator:

Manifest https://ca.rg.net/rrdp/notify.xml for this certificate is not available at repository {1}.

When I try to curl the file, I need to specify the -k option because the SSL cert is self-signed.

Is there any way to bypass this issue?

**Comment by dacruz** [comment]
Can you check the property rpki.validator.rrdp.trust.all.tls.certificates=true ?
On my instance, I have the same Manifest issue. But the notification.xml loads as expected.

**Comment by dacruz** [comment]
I just noticed that the missing manifest is under rsync://ca.rg.net/rpki/**RGnet**/ and not rsync://ca.rg.net/rpki/**RGnet-OU**

```
$ rsync -r rsync://ca.rg.net/rpki/RGnet/
rsync: change_dir "/RGnet" (in rpki) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1679) [Receiver=3.1.3]
```

```
$ rsync -r rsync://ca.rg.net/rpki/RGnet-OU
drwxr-xr-x          4,096 2019/06/18 05:12:23 RGnet-OU
-rw-r--r--          1,730 2019/06/16 04:40:04 RGnet-OU/4DAr1VXnjh69GoQkxjmIQdkRVtQ.roa
-rw-r--r--          1,769 2019/06/16 04:40:04 RGnet-OU/Hf1ZR31W9DN5QSF6xJEO5qgH4ac.roa
-rw-r--r--            455 2019/06/18 05:12:23 RGnet-OU/RjQZ5pSL7riIcFGhdm4iFtIalko.crl
-rw-r--r--          2,212 2019/06/18 05:12:23 RGnet-OU/RjQZ5pSL7riIcFGhdm4iFtIalko.mft
-rw-r--r--          1,729 2019/06/16 04:40:04 RGnet-OU/Zs_svFDVb-_DZnjgkN8DLKk_IRI.roa
-rw-r--r--          1,288 2019/06/17 15:12:17 RGnet-OU/aaI5ikDRYL7nJH9kwrv4b80iIAI.cer
-rw-r--r--          1,729 2019/06/16 04:40:04 RGnet-OU/xZEe_HUX98kANKreh2ZIpdaDnAI.roa
drwxr-xr-x          4,096 2019/06/18 05:12:20 RGnet-OU/ovsCA
-rw-r--r--            433 2019/06/18 05:12:20 RGnet-OU/ovsCA/aaI5ikDRYL7nJH9kwrv4b80iIAI.crl
-rw-r--r--          1,858 2019/06/18 05:12:20 RGnet-OU/ovsCA/aaI5ikDRYL7nJH9kwrv4b80iIAI.mft
```

**Comment by edugas** [comment]
I've added the property "rpki.validator.rrdp.trust.all.tls.certificates=true" and restarted the process but it still shows the same "Validation issues" error.

It loads the notify.xml from https://ca.rg.net/rrdp/notify.xml just fine (and it was loading fine before adding the property above) it just doesn't see to validate. I've attached a screenshot of the overview for RIPE NCC RPKI Root:

**Comment by lolepezy** [comment]
Should be solved by now.
