### ISSUE TITLE
SLURM file processing broken in 3.1

### ISSUE THREAD

**Issue by benmaddison** [RIPE-NCC/rpki-validator-3#94]
*version: 3.1-2019.07.23_15.00.28*

# summary
The `slurm.json` file created by the validator does not conform to https://tools.ietf.org/html/rfc8416, and the `api/slurm/upload` endpoint refuses to accept properly constructed SLURM files.
This issue was not present in version 3.0.

# example
The following was created by a running validator:
```json
{
  "slurmVersion": "1",
  "slurmTarget": [],
  "validationOutputFilters": {
    "prefixFilters": [
      {
        "asn": "AS37271",
        "prefix": "0.0.0.0/0"
      },
      {
        "asn": "AS37271",
        "prefix": "::/0"
      }
    ],
    "bgpsecFilters": []
  },
  "locallyAddedAssertions": {
    "prefixAssertions": [],
    "bgpsecAssertions": []
  }
}
```

# issues
- `slurmVersion` should be a number, not a string. https://tools.ietf.org/html/rfc8416#section-3.2
- `slurmTarget` property was removed in draft-ietf-sidr-slurm-08 and is not allowed in rfc8416.
- `asn` should be a number, not a string, and omit the leading "AS". https://tools.ietf.org/html/rfc8416#section-3.3.1
- only one of `asn` or `prefix` need be present in an object contained in prefix-filter entry, however the `api/slurm/upload` api endpoint refuses to accept an entry with only one present. https://tools.ietf.org/html/rfc8416#section-3.3.1

**Comment by benmaddison** [comment]
Any chance of some feedback here?

**Comment by lolepezy** [comment]
Hi Ben,

We will tackle this in the next two weeks sprint and release a fixed version not later than then end of it.

**Comment by benmaddison** [comment]
Thanks @lolepezy. Let me know if there's anything assistance I can provide.

**Comment by lolepezy** [comment]
Hi Ben,

Could you install the new version and see if it is fixed for you?
