### ISSUE TITLE
bgp-preview should not show default routes

### ISSUE THREAD

**Issue by job** [RIPE-NCC/rpki-validator-3#95]
The validator should not show `0.0.0.0/0` or `::/0` in context of `bgp-preview`. While default routes have a purpose in operations, they don't really serve a purpose in context of the `bgp-preview` feature in the validator. They don't add anything actionable, but they may be cause for confusion "why am I seeing this?"

example:
<img src="http://instituut.net/~job/screenshots/deb6e559ec1cd5a2.png" />

**Comment by lolepezy** [comment]
Hi Job,

This page is not actionable in principle, it essentially reflects the state of route collectors. While I do agree that it may be confusing (and nobody is going to create ROAs for 0/0 anyway), the purpose of this page is to literally show you all the announcements and if and how they are covered by ROAs. We will have an internal discussion about it and quite probably filter something out from there.

**Comment by job** [comment]
To reduce the confusion I would recommend to remove the default routes when importing the state of the collectors.

**Comment by lolepezy** [comment]
Default routes are filtered out in the latest version.
