### ISSUE TITLE
--privileged appears needed only because of systemd: can we avoid?

### ISSUE THREAD

**Issue by geeohgeegeeoh** [RIPE-NCC/rpki-validator-3#97]
If the Docker didn't use systemd, it wouldn't need --privileged. For kubernetes deploy, we think it might be better *not* to depend on this.

**Comment by lolepezy** [comment]
We have added this to our planning for the next development phase.

**Comment by wibisono** [comment]
We added [alpine](https://github.com/RIPE-NCC/rpki-validator-3-docker/tree/master/alpine) based docker image that does not require systemd.

Hopefully this will work for you, 

Cheers.
